"use client";

import React, { createContext, useContext, useState, useEffect } from "react";
import { useAuth } from "../lib/auth";
import { getUserItem, setUserItem } from "../lib/userStorage";

export type Locale = "es" | "en" | "pt" | "fr" | "de" | "it" | "zh" | "ja" | "ko" | "ru" | "hi" | "ar" | "tr";

export interface Language {
  code: Locale;
  name: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: "es", name: "Español", flag: "🇲🇽" },
  { code: "en", name: "English", flag: "🇺🇸" },
];

const MVP_LOCALES = new Set<Locale>(LANGUAGES.map((language) => language.code));

export const TRANSLATIONS: Record<Locale, Record<string, string>> = {
  es: {
    // Nav / Common
    options: "Opciones",
    batch: "Batch",
    evaluation: "Evaluación",
    moldex: "Moldex",
    support: "Soporte",
    logout: "Salir",
    login: "Entrar",
    welcome: "Bienvenido",
    close: "Cerrar",
    save: "Guardar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    error: "Error",
    success: "Éxito",

    // Landing Page
    // NARRATIVA. Lo que este producto es, y lo que NO afirma ser. No descubre
    // fármacos, no predice eficacia y no sustituye un experimento: prepara
    // hipótesis, ejecuta evaluaciones iniciales y entrega evidencia que otro
    // puede verificar. Cualquier texto que prometa más de eso hay que
    // corregirlo aquí, no matizarlo con una nota al pie.
    hero_tagline: "HERRAMIENTA LOCAL Y ABIERTA",
    hero_title_1: "PREPARA",
    hero_title_2: "EVALÚA",
    hero_title_3: "DOCUMENTA",
    hero_desc: "Una herramienta local y abierta para preparar hipótesis estructurales, ejecutar evaluaciones iniciales y entregar evidencia computacional reproducible. No descubre fármacos ni predice eficacia clínica, y no sustituye a un experimento.",
    hero_button_edu: "Modo Estudiante",
    hero_button_pro: "Evaluación Avanzada",
    features_title: "Qué hace, exactamente",
    step_01_title: "Evaluación por caso",
    step_01_desc: "Un receptor, un ligando y una hipótesis declarada. La comprobación previa dice qué va a entrar en la corrida antes de ejecutarla.",
    step_02_title: "Cohortes comparables",
    step_02_desc: "Muchas moléculas bajo un único receptor y una configuración común, con su cobertura, sus excepciones y sus duplicados declarados.",
    step_03_title: "Dossier y paquete reproducible",
    step_03_desc: "Un PDF que dice qué se calculó y qué quedó sin evaluar, y un ZIP con manifiesto y hashes que un tercero puede verificar sin ejecutar nada.",
    step_04_title: "Ejecución local",
    step_04_desc: "El motor corre en este equipo. Ningún dato molecular sale de aquí salvo que tú lo exportes.",
    step_05_title: "Límites científicos declarados",
    step_05_desc: "Completar un acoplamiento no demuestra actividad. Lo que no se comprobó aparece como NO EVALUADO, no como aprobado.",
    stats_molecules: "Moléculas Evaluadas",
    stats_best_score: "Mejor afinidad observada (kcal/mol)",
    stats_certified: "Integridad registrada",

    // Options Panel
    opt_appearance: "Apariencia",
    opt_theme: "Tema",
    opt_theme_dark: "Oscuro",
    opt_theme_light: "Claro",
    opt_interface: "Interfaz",
    opt_sounds: "Sonidos de Interfaz",
    opt_sounds_muted: "Sonidos silenciados",
    opt_sounds_active: "Sonidos activos",
    opt_sounds_activate: "Clic para activar",
    opt_sounds_silence: "Clic para silenciar",
    opt_ai: "Intérprete IA",
    opt_ai_config: "Configurar proveedor IA",
    opt_ai_chat_open: "Abrir MolChat",
    opt_ai_chat_close: "Cerrar MolChat",
    opt_data: "Datos y Respaldo",
    opt_data_export: "Exportar Bioteca (JSON)",
    opt_data_export_desc: "Descarga todas tus moléculas y resultados en un archivo portátil",
    opt_data_export_success: "Respaldo exportado correctamente",
    opt_data_reset: "Restablecer datos de sesión",
    opt_data_reset_desc: "Cierra la sesión local activa. El historial de evaluaciones permanece en la base de datos.",
    opt_data_reset_warning: "Esta acción cerrará tu sesión local. Tus evaluaciones y moléculas no se eliminarán.",
    opt_data_reset_success: "Sesión restablecida",
    opt_legal: "Legal e Información",
    opt_legal_terms: "Términos y Privacidad",
    opt_legal_about: "Acerca de",

    // Legal / Terms Modal
    legal_title: "Marco Legal — MolDesign AI",
    legal_tab_terms: "Términos de Uso",
    legal_tab_priv: "Privacidad",
    legal_tab_lic: "Licencia",
    legal_local_first: "Local-First · Sin Telemetría · 100% Offline",
    legal_understood: "Entendido",

    // Login Page
    login_title: "Inicio de Sesión Local",
    login_subtitle: "MolDesign funciona de forma 100% local en tu dispositivo.",
    login_username: "Nombre de Usuario",
    login_password: "Contraseña (Mínimo 4 caracteres)",
    login_btn: "Acceder al Laboratorio",
    login_privacy_badge: "Tus datos nunca salen de este dispositivo.",
    login_error_fields: "Por favor, completa todos los campos correctamente.",
    login_error_auth: "Credenciales incorrectas.",

    // Evaluation Page
    eval_title: "Panel de Evaluación Molecular",
    eval_draw_tab: "1. Dibujar Molécula",
    eval_target_tab: "2. Seleccionar Blanco",
    eval_run_tab: "3. Simulación & Score",
    eval_results_tab: "4. Reporte Final",
    eval_target_select_title: "Selecciona el Blanco de Acoplamiento",
    eval_target_desc: "Selecciona el receptor proteico contra el cual se simulará el acoplamiento molecular (docking).",
    eval_run_simulation: "Iniciar Simulación Científica",
    eval_docking_progress: "Simulando acoplamiento molecular...",
    eval_docking_success: "Acoplamiento molecular completado con éxito.",
    eval_docking_fail: "Error durante la simulación de acoplamiento.",
    eval_vina_score: "Afinidad de Vina",
    eval_admet_score: "Propiedades ADMET",
    eval_solana_status: "Registro experimental en Solana",
    eval_solana_btn: "Probar registro en devnet",

    // ── Ayudas contextuales (los "?") ─────────────────────────────
    // Cada una desactiva UNA lectura equivocada concreta. Si un texto no
    // corrige un malentendido real, no lleva "?".
    ayuda_ensemble_titulo: "Generación conformacional",
    ayuda_ensemble: "El acoplamiento parte de una conformación 3D del ligando. Con «ensemble» se generan K y cada una se acopla por separado; las poses se juntan y se reordenan por afinidad. Amplía la COBERTURA: sube la probabilidad de que alguna conformación se parezca a la real. En la medición interna NO mejoró la elección de la pose top-1 — el cuello de botella se desplaza a la selección. Compra amplitud de búsqueda, no precisión, y cuesta K veces el tiempo de docking.",

    ayuda_exhaustividad_titulo: "Exhaustividad y semilla",
    ayuda_exhaustividad: "La exhaustividad es cuánto busca Vina dentro de la caja. Más búsqueda reduce la probabilidad de perderse una pose por azar, pero no corrige un sitio mal definido ni una preparación dudosa. La semilla fija el azar: sin ella la corrida no se puede repetir bit a bit.",

    ayuda_afinidad_titulo: "Afinidad Vina observada",
    ayuda_afinidad: "Es el valor que la función de puntuación de Vina asignó a esta pose, en kcal/mol. NO es una energía libre de unión medida, ni se convierte en Ki o IC50. Sirve para ordenar poses dentro de esta misma corrida; comparar entre receptores o protocolos distintos no está justificado.",

    ayuda_margen_titulo: "Margen del selector",
    ayuda_margen: "Es la distancia entre la primera y la segunda pose según el modelo de selección. NO es una probabilidad ni una nota: un margen alto dice que el modelo separó claramente, no que acertara. Por debajo del umbral el selector se abstiene, y la referencia vuelve a ser Vina top-1.",

    ayuda_estados_titulo: "Revisión vs. no evaluada",
    ayuda_estados: "«Controles superados» es lo único que autoriza llamar válida a una pose. «Requiere revisión» significa que la batería no corrió entera — no que la pose sea buena. «No evaluada» describe lo que le pasó al VALIDADOR, nunca a la molécula: ninguna de las dos es evidencia negativa sobre el compuesto.",

    ayuda_cobertura_titulo: "Cobertura evaluada",
    ayuda_cobertura: "Cuántas poses recibieron veredicto físico, sobre cuántas produjo la corrida. El denominador importa: «todas superadas» sobre 2 de 9 poses no dice nada de las 7 restantes. Por eso se muestran las dos cifras y nunca un porcentaje suelto.",

    ayuda_checksums_titulo: "Checksums del paquete",
    ayuda_checksums: "Demuestran INTEGRIDAD: que los bytes no cambiaron desde que se generó el paquete. No demuestran que el método fuera adecuado, que la preparación fuera correcta ni que la conclusión sea cierta. Que un paquete sea «válido» es una afirmación sobre los archivos, no sobre la ciencia.",

    // ── Evidencia estructural (P0-C) ──────────────────────────────
    // Español e inglés se mantienen en paralelo a propósito: una prueba
    // comprueba que ninguna clave `se_` existe sólo en un idioma.
    se_title: "Evidencia estructural",
    se_subtitle: "Cómo se generaron las poses, cuál se sugiere y qué controles físicos superó.",
    se_disclaimer: "Describe lo que esta corrida midió. No afirma actividad biológica, potencia ni éxito farmacológico.",
    se_legacy: "Corrida anterior a estas etapas",
    se_legacy_note: "Esta evaluación se ejecutó antes de que existieran la validación física y el selector de pose. No es que fallaran: no llegaron a ejecutarse.",
    se_empty: "Esta corrida no dejó poses ni contratos que mostrar.",
    se_loading: "Cargando evidencia estructural…",
    se_error: "No se pudo leer la evidencia estructural de esta corrida.",
    se_show_detail: "Ver detalle",
    se_hide_detail: "Ocultar detalle",
    se_not_reported: "No informado",
    se_technical: "Detalles técnicos",
    se_s1_title: "Generación",
    se_s1_lead: "Qué produjo el acoplamiento y con qué protocolo.",
    se_gen_poses: "Poses producidas",
    se_gen_affinity: "Mejor afinidad Vina observada",
    se_gen_affinity_note: "Es lo que Vina observó, no una medición experimental de energía libre.",
    se_gen_gap: "Δ pose 1–2",
    se_gen_protocol: "Protocolo",
    se_gen_seed: "Semilla",
    se_gen_parser: "Lectura de poses",
    se_gen_conformers: "Conformeros / restarts",
    se_gen_conformers_absent: "No registrados por esta corrida",
    se_gen_conformers_note: "El resultado no persiste estos parámetros. No se rellenan con la configuración del caso: sería atribuir a esta corrida un ajuste que nadie guardó con ella.",
    se_gen_receptor: "Receptor preparado",
    se_gen_receptor_absent: "Sin huella del receptor",
    se_gen_provenance: "Trazas de reproducibilidad",
    se_gen_no_poses: "El acoplamiento no conservó ninguna pose.",
    se_s2_title: "Selección",
    se_s2_lead: "El selector recomienda; no sustituye. La pose principal sigue siendo la de Vina.",
    se_sel_selected: "El selector recomienda una pose",
    se_sel_abstained: "El selector se abstuvo",
    se_sel_unavailable: "Selector no disponible",
    se_sel_error: "El selector falló",
    se_sel_vina_top1: "Vina top-1 (original)",
    se_sel_suggested: "Pose sugerida",
    se_sel_would_have: "Habría sugerido",
    se_sel_no_recommendation: "Sin recomendación",
    se_sel_confidence: "Margen de confianza",
    se_sel_threshold: "umbral",
    se_sel_confidence_note: "Es la distancia entre la primera y la segunda pose según el selector. No es una probabilidad ni una nota.",
    se_sel_model: "Modelo",
    se_sel_fallback: "Referencia: Vina top-1 (fallback)",
    se_sel_fallback_note: "No es un acierto del selector: es lo que queda cuando no hay recomendación.",
    se_sel_diverge: "La pose sugerida NO es la top-1 de Vina",
    se_sel_diverge_note: "Las dos se conservan y las dos se enseñan. La pose principal del producto sigue siendo la de Vina; la sugerida es una recomendación que puedes comparar.",
    se_sel_agree: "La pose sugerida coincide con la top-1 de Vina",
    se_sel_abstain_reason: "Razón",
    se_sel_scores: "Puntuación del selector por pose",
    se_sel_warnings: "Avisos del selector",
    se_reason_MODELO_AUSENTE: "El modelo del selector no está en este equipo.",
    se_reason_SIN_POSES: "La corrida no conservó ninguna pose.",
    se_reason_SIN_PDBQT_DE_POSE: "Alguna pose no conservó sus coordenadas, y el selector necesita las de todas para comparar.",
    se_reason_RECEPTOR_NO_DISPONIBLE: "No se pudo usar el receptor exacto de esta corrida, y el selector no opina sobre otro.",
    se_reason_SELECTOR_FALLO: "El selector no pudo evaluar estas poses.",
    se_reason_MARGEN_BAJO_UMBRAL: "El margen entre la primera y la segunda no llega al umbral de abstención.",
    se_reason_UNA_SOLA_POSE: "Una sola pose: no hay margen que medir.",
    se_reason_SELECCION_AUSENTE: "Esta evaluación es anterior a la etapa de selección de pose.",
    se_reason_RECEPTOR_AUSENTE: "El receptor preparado de esta corrida no está disponible.",
    se_reason_RECEPTOR_NO_COINCIDE: "El receptor del catálogo ya no es el que se acopló; validar contra otro daría un veredicto sobre un sistema distinto.",
    se_reason_RECEPTOR_SIN_HUELLA: "La corrida no registró el hash del receptor, así que no se puede demostrar cuál se usó.",
    se_reason_SIN_PLANTILLA: "No hay plantilla química declarada para reconstruir la pose; el grafo no se adivina.",
    se_reason_MAPA_SIN_HIDROGENOS_POLARES: "El mapa atómico no cubre los hidrógenos polares de la pose.",
    se_reason_VALIDADOR_NO_DISPONIBLE: "El validador físico no está disponible en este equipo.",
    se_reason_EVIDENCIA_AUSENTE: "Esta evaluación es anterior a la etapa de validación física.",

    // ── Controles de PoseBusters, dichos en español ───────────────────────
    //
    // Son los nombres de columna que devuelve PoseBusters 0.6.5 tal cual, y la
    // interfaz los imprimía crudos: en una pantalla en español aparecía
    // «Controles que fallan: minimum_distance_to_protein, internal_steric_clash».
    // El identificador sigue estando —va en el `title` de la línea y en el
    // dossier— porque es el que permite reproducir el control; lo que cambia es
    // lo que se lee.
    se_check_mol_pred_loaded: "Carga de la pose",
    se_check_mol_true_loaded: "Carga de la referencia",
    se_check_mol_cond_loaded: "Carga del receptor",
    se_check_sanitization: "Saneamiento químico (RDKit)",
    se_check_inchi_convertible: "Convertible a InChI",
    se_check_all_atoms_connected: "Todos los átomos conectados",
    se_check_no_radicals: "Sin radicales libres",
    se_check_bond_lengths: "Longitudes de enlace",
    se_check_bond_angles: "Ángulos de enlace",
    se_check_internal_steric_clash: "Choque estérico interno",
    se_check_aromatic_ring_flatness: "Planaridad de anillos aromáticos",
    "se_check_non-aromatic_ring_non-flatness": "No planaridad de anillos no aromáticos",
    se_check_double_bond_flatness: "Planaridad de dobles enlaces",
    se_check_internal_energy: "Energía interna del confórmero",
    "se_check_protein-ligand_maximum_distance": "Distancia máxima al receptor",
    se_check_minimum_distance_to_protein: "Distancia mínima a la proteína",
    se_check_minimum_distance_to_organic_cofactors: "Distancia mínima a cofactores orgánicos",
    se_check_minimum_distance_to_inorganic_cofactors: "Distancia mínima a cofactores inorgánicos",
    se_check_minimum_distance_to_waters: "Distancia mínima a las aguas",
    se_check_volume_overlap_with_protein: "Solapamiento de volumen con la proteína",
    se_check_volume_overlap_with_organic_cofactors: "Solapamiento de volumen con cofactores orgánicos",
    se_check_volume_overlap_with_inorganic_cofactors: "Solapamiento de volumen con cofactores inorgánicos",
    se_check_volume_overlap_with_waters: "Solapamiento de volumen con las aguas",
    se_s3_title: "Controles físicos",
    se_s3_lead: "Qué comprobó el validador sobre cada pose, y qué no pudo comprobar.",
    se_phys_passed: "Controles superados",
    se_phys_failed: "Controles fallidos",
    se_phys_review: "Requiere revisión",
    se_phys_not_evaluated: "No evaluada",
    se_phys_coverage: "Cobertura evaluada",
    se_phys_poses_unit: "poses",
    se_phys_engine: "Motor de validación",
    se_phys_failing: "Controles que fallan",
    se_phys_none_failing: "Ningún control de química o geometría falla.",
    se_phys_counts: "Desglose",
    se_phys_count_pass: "pasan",
    se_phys_count_fail: "fallan",
    se_phys_count_skip: "sin evaluar",
    se_phys_suggested_status: "Estado físico de la pose sugerida",
    se_phys_review_note: "La pose sugerida no está confirmada como físicamente válida, y no se sustituye por otra. Elegir «la siguiente que pase» sería una decisión que nadie tomó y para la que el modelo no fue entrenado.",
    se_phys_absent: "Esta corrida no ejecutó los controles físicos.",
    se_phys_review_meaning: "“Requiere revisión” significa que la batería no corrió entera. No es una pose aprobada.",
    se_phys_not_evaluated_meaning: "“No evaluada” describe lo que le pasó al validador, nunca a la molécula.",
    se_phys_per_pose: "Veredicto por pose",
    se_phys_open_in_structure: "Consulta los controles individuales desde Estructura y evidencia.",
    se_phys_reason: "Razón de la abstención",
    se_s4_title: "Decisión justificable",
    se_s4_lead: "Qué se puede sostener con esta evidencia, y qué queda abierto.",
    se_dec_established: "Qué evidencia existe",
    se_dec_uncertainties: "Incertidumbres abiertas",
    se_dec_no_uncertainties: "No quedan incertidumbres más allá de los límites generales del protocolo.",
    se_dec_alternatives: "Alternativas físicamente válidas",
    se_dec_alternatives_note: "Se listan para que puedas compararlas. Ninguna se selecciona automáticamente.",
    se_dec_no_alternatives: "Ninguna otra pose superó los controles físicos.",
    se_dec_next: "Próximo paso recomendado",
    se_dec_next_abstain: "Abstenerse: completar la corrida",
    se_dec_next_abstain_detail: "No priorizar el ligando ni encadenar cálculos posteriores mientras falten poses o haya controles fallidos.",
    se_dec_next_review: "Revisar la geometría antes de continuar",
    se_dec_next_review_detail: "Resolver los controles pendientes antes de MM-GBSA, dinámica molecular o cualquier priorización experimental.",
    se_dec_next_proceed: "Apta para análisis posterior dentro del mismo protocolo",
    se_dec_next_proceed_detail: "La evidencia disponible permite continuar conservando las limitaciones documentadas. No dice que la molécula sea activa.",
    se_ev_poses_generated: "Se generaron poses con su afinidad Vina observada.",
    se_ev_physical_checks_run: "Los controles físicos se ejecutaron sobre las poses de esta corrida.",
    se_ev_selector_ran: "El selector de pose se ejecutó y dejó su veredicto.",
    se_ev_provenance_sealed: "El receptor de la corrida quedó sellado por su hash.",
    se_unc_no_physical_validation: "Ninguna pose recibió veredicto físico.",
    se_unc_partial_coverage: "Sólo una parte de las poses recibió veredicto.",
    se_unc_suggested_pose_not_passed: "La pose sugerida no está confirmada como físicamente válida.",
    se_unc_selector_abstained: "El selector no recomendó ninguna pose.",
    se_unc_selector_unavailable: "El selector no se ejecutó en esta corrida.",
    se_unc_selector_error: "El selector falló, así que no hay recomendación que leer.",
    se_unc_selection_diverges: "La pose sugerida y la top-1 de Vina no son la misma.",
    se_unc_single_pose: "Con una sola pose no hay separación interna que medir.",
    se_unc_near_tie: "Varias poses quedan a 1 kcal/mol o menos; quedarse con una sola es ambiguo.",
    se_unc_incomplete_provenance: "La traza de reproducibilidad está incompleta.",
    se_unc_no_seed: "La corrida no registró la semilla, así que no se puede repetir bit a bit.",
    se_cmp_title: "Comparar poses",
    se_cmp_lead: "Top-1 de Vina, pose sugerida y alternativas, una al lado de otra.",
    se_cmp_rank: "Pose",
    se_cmp_affinity: "Afinidad Vina",
    se_cmp_selector: "Selector",
    se_cmp_physical: "Controles físicos",
    se_cmp_role: "Papel",
    se_cmp_role_top1: "Vina top-1",
    se_cmp_role_suggested: "Sugerida",
    se_cmp_role_alternative: "Alternativa",

    // Moldex / Targets Page
    moldex_title: "Biblioteca de Blancos Moleculares (Moldex)",
    moldex_search: "Buscar blanco...",
    moldex_table_pdb: "ID PDB",
    moldex_table_name: "Nombre del Receptor",
    moldex_table_type: "Tipo",
    moldex_table_resolution: "Resolución",
  },
  en: {
    options: "Options",
    batch: "Batch",
    evaluation: "Evaluation",
    moldex: "Moldex",
    support: "Support",
    logout: "Log Out",
    login: "Log In",
    welcome: "Welcome",
    close: "Close",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    error: "Error",
    success: "Success",

    hero_tagline: "Local, open tool",
    hero_title_1: "Prepare",
    hero_title_2: "Evaluate",
    hero_title_3: "Document",
    hero_desc: "A local, open tool to prepare structural hypotheses, run initial evaluations and deliver reproducible computational evidence. It does not discover drugs, does not predict clinical efficacy, and does not replace an experiment.",
    hero_button_edu: "Student Mode",
    hero_button_pro: "Advanced Evaluation",
    features_title: "What it does, exactly",
    step_01_title: "Case-based evaluation",
    step_01_desc: "One receptor, one ligand and a declared hypothesis. The preflight says what will enter the run before running it.",
    step_02_title: "Comparable cohorts",
    step_02_desc: "Many molecules under a single receptor and a common configuration, with declared coverage, exceptions and duplicates.",
    step_03_title: "Dossier and reproducible package",
    step_03_desc: "A PDF stating what was computed and what was left unevaluated, plus a ZIP with manifest and hashes a third party can verify without running anything.",
    step_04_title: "Local execution",
    step_04_desc: "The engine runs on this machine. No molecular data leaves it unless you export it.",
    step_05_title: "Declared scientific limits",
    step_05_desc: "Completing a docking run does not demonstrate activity. What was not checked shows as NOT EVALUATED, never as approved.",
    stats_molecules: "Evaluated Molecules",
    stats_best_score: "Best observed affinity (kcal/mol)",
    stats_certified: "Integrity registered",

    opt_appearance: "Appearance",
    opt_theme: "Theme",
    opt_theme_dark: "Dark",
    opt_theme_light: "Light",
    opt_interface: "Interface",
    opt_sounds: "Interface Sounds",
    opt_sounds_muted: "Sounds muted",
    opt_sounds_active: "Sounds active",
    opt_sounds_activate: "Click to activate",
    opt_sounds_silence: "Click to mute",
    opt_ai: "AI Interpreter",
    opt_ai_config: "Configure AI provider",
    opt_ai_chat_open: "Open MolChat",
    opt_ai_chat_close: "Close MolChat",
    opt_data: "Data & Backup",
    opt_data_export: "Export Library (JSON)",
    opt_data_export_desc: "Download all your molecules and results in a portable file",
    opt_data_export_success: "Backup exported successfully",
    opt_data_reset: "Reset session data",
    opt_data_reset_desc: "Closes active local session. Evaluation history remains intact in database.",
    opt_data_reset_warning: "This action will log you out. Your evaluations and molecules will not be deleted.",
    opt_data_reset_success: "Session reset",
    opt_legal: "Legal & Info",
    opt_legal_terms: "Terms & Privacy",
    opt_legal_about: "About",

    legal_title: "Legal Framework — MolDesign AI",
    legal_tab_terms: "Terms of Use",
    legal_tab_priv: "Privacy",
    legal_tab_lic: "License",
    legal_local_first: "Local-First · No Telemetry · 100% Offline",
    legal_understood: "Understood",

    login_title: "Local Login",
    login_subtitle: "MolDesign works 100% locally on your device.",
    login_username: "Username",
    login_password: "Password (Min 4 characters)",
    login_btn: "Access Laboratory",
    login_privacy_badge: "Your data never leaves this device.",
    login_error_fields: "Please complete all fields correctly.",
    login_error_auth: "Incorrect credentials.",

    eval_title: "Molecular Evaluation Panel",
    eval_draw_tab: "1. Draw Molecule",
    eval_target_tab: "2. Select Target",
    eval_run_tab: "3. Simulation & Score",
    eval_results_tab: "4. Final Report",
    eval_target_select_title: "Select Docking Target",
    eval_target_desc: "Select which protein receptor to simulate molecular docking against.",
    eval_run_simulation: "Start Scientific Simulation",
    eval_docking_progress: "Simulating molecular docking...",
    eval_docking_success: "Molecular docking completed successfully.",
    eval_docking_fail: "Error during docking simulation.",
    eval_vina_score: "Vina Affinity",
    eval_admet_score: "ADMET Properties",
    eval_solana_status: "Experimental Solana record",
    eval_solana_btn: "Test devnet record",

    // ── Contextual help (the "?") ─────────────────────────────────
    ayuda_ensemble_titulo: "Conformer generation",
    ayuda_ensemble: "Docking starts from one 3D conformation of the ligand. With \"ensemble\", K are generated and each is docked separately; the poses are pooled and re-ranked by affinity. It widens COVERAGE: it raises the chance that some conformation resembles the real one. In our internal measurement it did NOT improve the top-1 pick — the bottleneck moves to selection. It buys breadth of search, not precision, and costs K times the docking time.",

    ayuda_exhaustividad_titulo: "Exhaustiveness and seed",
    ayuda_exhaustividad: "Exhaustiveness is how hard Vina searches inside the box. More search lowers the chance of missing a pose by luck, but it does not fix a badly defined site or a doubtful preparation. The seed pins the randomness: without it the run cannot be repeated bit for bit.",

    ayuda_afinidad_titulo: "Observed Vina affinity",
    ayuda_afinidad: "The value Vina's scoring function assigned to this pose, in kcal/mol. It is NOT a measured binding free energy, and it does not convert into Ki or IC50. It orders poses within this same run; comparing across receptors or protocols is not justified.",

    ayuda_margen_titulo: "Selector margin",
    ayuda_margen: "The distance between the first and second pose according to the selection model. It is NOT a probability or a grade: a wide margin says the model separated them clearly, not that it was right. Below the threshold the selector abstains, and the reference goes back to Vina top-1.",

    ayuda_estados_titulo: "Review vs. not evaluated",
    ayuda_estados: "\"Checks passed\" is the only thing that licenses calling a pose valid. \"Needs review\" means the battery did not run in full — not that the pose is good. \"Not evaluated\" describes what happened to the VALIDATOR, never to the molecule: neither is negative evidence about the compound.",

    ayuda_cobertura_titulo: "Evaluated coverage",
    ayuda_cobertura: "How many poses received a physical verdict, out of how many the run produced. The denominator matters: \"all passed\" over 2 of 9 poses says nothing about the other 7. That is why both figures are shown and never a bare percentage.",

    ayuda_checksums_titulo: "Package checksums",
    ayuda_checksums: "They prove INTEGRITY: that the bytes have not changed since the package was generated. They do not prove the method was adequate, the preparation correct, or the conclusion true. A package being \"valid\" is a claim about the files, not about the science.",

    // ── Structural evidence (P0-C) ────────────────────────────────
    // Kept in lockstep with the Spanish block on purpose: a test asserts
    // that no `se_` key exists in only one language.
    se_title: "Structural evidence",
    se_subtitle: "How the poses were generated, which one is suggested, and which physical checks it passed.",
    se_disclaimer: "Describes what this run measured. It claims no biological activity, potency or pharmacological success.",
    se_legacy: "Run predates these stages",
    se_legacy_note: "This evaluation ran before physical validation and the pose selector existed. They did not fail: they never ran.",
    se_empty: "This run left no poses or contracts to show.",
    se_loading: "Loading structural evidence…",
    se_error: "The structural evidence for this run could not be read.",
    se_show_detail: "Show detail",
    se_hide_detail: "Hide detail",
    se_not_reported: "Not reported",
    se_technical: "Technical details",
    se_s1_title: "Generation",
    se_s1_lead: "What the docking produced, and under which protocol.",
    se_gen_poses: "Poses produced",
    se_gen_affinity: "Best observed Vina affinity",
    se_gen_affinity_note: "This is what Vina observed, not an experimental free-energy measurement.",
    se_gen_gap: "Δ pose 1–2",
    se_gen_protocol: "Protocol",
    se_gen_seed: "Random seed",
    se_gen_parser: "Pose parsing",
    se_gen_conformers: "Conformers / restarts",
    se_gen_conformers_absent: "Not recorded by this run",
    se_gen_conformers_note: "The result does not persist these parameters. They are not filled in from the case configuration: that would attribute to this run a setting nobody saved with it.",
    se_gen_receptor: "Prepared receptor",
    se_gen_receptor_absent: "No receptor fingerprint",
    se_gen_provenance: "Reproducibility traces",
    se_gen_no_poses: "The docking kept no poses.",
    se_s2_title: "Selection",
    se_s2_lead: "The selector recommends; it does not replace. The primary pose is still Vina's.",
    se_sel_selected: "The selector recommends a pose",
    se_sel_abstained: "The selector abstained",
    se_sel_unavailable: "Selector unavailable",
    se_sel_error: "The selector failed",
    se_sel_vina_top1: "Vina top-1 (original)",
    se_sel_suggested: "Suggested pose",
    se_sel_would_have: "Would have suggested",
    se_sel_no_recommendation: "No recommendation",
    se_sel_confidence: "Confidence margin",
    se_sel_threshold: "threshold",
    se_sel_confidence_note: "The distance between the first and second pose according to the selector. It is not a probability or a grade.",
    se_sel_model: "Model",
    se_sel_fallback: "Reference: Vina top-1 (fallback)",
    se_sel_fallback_note: "Not a selector success: it is what remains when there is no recommendation.",
    se_sel_diverge: "The suggested pose is NOT Vina's top-1",
    se_sel_diverge_note: "Both are kept and both are shown. The product's primary pose is still Vina's; the suggested one is a recommendation you can compare.",
    se_sel_agree: "The suggested pose matches Vina's top-1",
    se_sel_abstain_reason: "Reason",
    se_sel_scores: "Selector score per pose",
    se_sel_warnings: "Selector warnings",
    se_reason_MODELO_AUSENTE: "The selector model is not present on this machine.",
    se_reason_SIN_POSES: "The run kept no poses.",
    se_reason_SIN_PDBQT_DE_POSE: "Some pose did not keep its coordinates, and the selector needs all of them to compare.",
    se_reason_RECEPTOR_NO_DISPONIBLE: "The exact receptor of this run could not be used, and the selector will not opine on a different one.",
    se_reason_SELECTOR_FALLO: "The selector could not evaluate these poses.",
    se_reason_MARGEN_BAJO_UMBRAL: "The margin between the first and second pose does not reach the abstention threshold.",
    se_reason_UNA_SOLA_POSE: "A single pose: there is no margin to measure.",
    se_reason_SELECCION_AUSENTE: "This evaluation predates the pose selection stage.",
    se_reason_RECEPTOR_AUSENTE: "The prepared receptor for this run is not available.",
    se_reason_RECEPTOR_NO_COINCIDE: "The catalogue receptor is no longer the one that was docked; validating against another would judge a different system.",
    se_reason_RECEPTOR_SIN_HUELLA: "The run did not record the receptor hash, so there is no proof of which one was used.",
    se_reason_SIN_PLANTILLA: "No chemical template is declared to rebuild the pose; the graph is never guessed.",
    se_reason_MAPA_SIN_HIDROGENOS_POLARES: "The atom map does not cover the polar hydrogens of the pose.",
    se_reason_VALIDADOR_NO_DISPONIBLE: "The physical validator is not available on this machine.",
    se_reason_EVIDENCIA_AUSENTE: "This evaluation predates the physical validation stage.",

    // PoseBusters column names, spelled out. English readers get the same
    // treatment as Spanish ones: a sentence, not an identifier.
    se_check_mol_pred_loaded: "Pose loaded",
    se_check_mol_true_loaded: "Reference loaded",
    se_check_mol_cond_loaded: "Receptor loaded",
    se_check_sanitization: "Chemical sanitization (RDKit)",
    se_check_inchi_convertible: "InChI convertible",
    se_check_all_atoms_connected: "All atoms connected",
    se_check_no_radicals: "No free radicals",
    se_check_bond_lengths: "Bond lengths",
    se_check_bond_angles: "Bond angles",
    se_check_internal_steric_clash: "Internal steric clash",
    se_check_aromatic_ring_flatness: "Aromatic ring flatness",
    "se_check_non-aromatic_ring_non-flatness": "Non-aromatic ring non-flatness",
    se_check_double_bond_flatness: "Double bond flatness",
    se_check_internal_energy: "Conformer internal energy",
    "se_check_protein-ligand_maximum_distance": "Maximum distance to the receptor",
    se_check_minimum_distance_to_protein: "Minimum distance to protein",
    se_check_minimum_distance_to_organic_cofactors: "Minimum distance to organic cofactors",
    se_check_minimum_distance_to_inorganic_cofactors: "Minimum distance to inorganic cofactors",
    se_check_minimum_distance_to_waters: "Minimum distance to waters",
    se_check_volume_overlap_with_protein: "Volume overlap with protein",
    se_check_volume_overlap_with_organic_cofactors: "Volume overlap with organic cofactors",
    se_check_volume_overlap_with_inorganic_cofactors: "Volume overlap with inorganic cofactors",
    se_check_volume_overlap_with_waters: "Volume overlap with waters",
    se_s3_title: "Physical checks",
    se_s3_lead: "What the validator checked on each pose, and what it could not check.",
    se_phys_passed: "Checks passed",
    se_phys_failed: "Checks failed",
    se_phys_review: "Needs review",
    se_phys_not_evaluated: "Not evaluated",
    se_phys_coverage: "Evaluated coverage",
    se_phys_poses_unit: "poses",
    se_phys_engine: "Validation engine",
    se_phys_failing: "Failing checks",
    se_phys_none_failing: "No chemistry or geometry check fails.",
    se_phys_counts: "Breakdown",
    se_phys_count_pass: "pass",
    se_phys_count_fail: "fail",
    se_phys_count_skip: "not evaluated",
    se_phys_suggested_status: "Physical status of the suggested pose",
    se_phys_review_note: "The suggested pose is not confirmed physically valid, and it is not swapped for another. Picking “the next one that passes” would be a decision nobody made and one the model was not trained for.",
    se_phys_absent: "This run did not execute the physical checks.",
    se_phys_review_meaning: "“Needs review” means the battery did not run in full. It is not an approved pose.",
    se_phys_not_evaluated_meaning: "“Not evaluated” describes what happened to the validator, never to the molecule.",
    se_phys_per_pose: "Verdict per pose",
    se_phys_open_in_structure: "See individual checks in Structure and evidence.",
    se_phys_reason: "Abstention reason",
    se_s4_title: "Justifiable decision",
    se_s4_lead: "What this evidence supports, and what remains open.",
    se_dec_established: "What evidence exists",
    se_dec_uncertainties: "Open uncertainties",
    se_dec_no_uncertainties: "No uncertainties remain beyond the protocol's general limits.",
    se_dec_alternatives: "Physically valid alternatives",
    se_dec_alternatives_note: "Listed so you can compare them. None is selected automatically.",
    se_dec_no_alternatives: "No other pose passed the physical checks.",
    se_dec_next: "Recommended next step",
    se_dec_next_abstain: "Abstain: complete the run",
    se_dec_next_abstain_detail: "Do not prioritise the ligand or chain further calculations while poses are missing or checks are failing.",
    se_dec_next_review: "Review the geometry before continuing",
    se_dec_next_review_detail: "Resolve the pending checks before MM-GBSA, molecular dynamics or any experimental prioritisation.",
    se_dec_next_proceed: "Suitable for further analysis within the same protocol",
    se_dec_next_proceed_detail: "The available evidence supports continuing while keeping the documented limitations. It does not say the molecule is active.",
    se_ev_poses_generated: "Poses were generated with their observed Vina affinity.",
    se_ev_physical_checks_run: "Physical checks ran on this run's poses.",
    se_ev_selector_ran: "The pose selector ran and left its verdict.",
    se_ev_provenance_sealed: "The run's receptor is sealed by its hash.",
    se_unc_no_physical_validation: "No pose received a physical verdict.",
    se_unc_partial_coverage: "Only some of the poses received a verdict.",
    se_unc_suggested_pose_not_passed: "The suggested pose is not confirmed physically valid.",
    se_unc_selector_abstained: "The selector recommended no pose.",
    se_unc_selector_unavailable: "The selector did not run for this evaluation.",
    se_unc_selector_error: "The selector failed, so there is no recommendation to read.",
    se_unc_selection_diverges: "The suggested pose and Vina's top-1 are not the same.",
    se_unc_single_pose: "With a single pose there is no internal separation to measure.",
    se_unc_near_tie: "Several poses lie within 1 kcal/mol; keeping only one is ambiguous.",
    se_unc_incomplete_provenance: "The reproducibility trace is incomplete.",
    se_unc_no_seed: "The run did not record the seed, so it cannot be repeated bit for bit.",
    se_cmp_title: "Compare poses",
    se_cmp_lead: "Vina top-1, the suggested pose and the alternatives, side by side.",
    se_cmp_rank: "Pose",
    se_cmp_affinity: "Vina affinity",
    se_cmp_selector: "Selector",
    se_cmp_physical: "Physical checks",
    se_cmp_role: "Role",
    se_cmp_role_top1: "Vina top-1",
    se_cmp_role_suggested: "Suggested",
    se_cmp_role_alternative: "Alternative",

    moldex_title: "Molecular Targets Library (Moldex)",
    moldex_search: "Search target...",
    moldex_table_pdb: "PDB ID",
    moldex_table_name: "Receptor Name",
    moldex_table_type: "Type",
    moldex_table_resolution: "Resolution",
  },
  pt: {
    options: "Opções",
    batch: "Lote",
    evaluation: "Avaliação",
    moldex: "Moldex",
    support: "Suporte",
    logout: "Sair",
    login: "Entrar",
    welcome: "Bem-vindo",
    close: "Fechar",
    save: "Salvar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    error: "Erro",
    success: "Sucesso",

    hero_tagline: "Laboratório Acadêmico",
    hero_title_1: "Projete seus",
    hero_title_2: "próprios",
    hero_title_3: "medicamentos",
    hero_desc: "Aprenda passo a passo como criar moléculas, avaliar se são viáveis e simular como interagem com receptores celulares.",
    hero_button_edu: "Modo Estudante",
    hero_button_pro: "Avaliação Avançada",
    features_title: "Fluxo de Trabalho Científico",
    step_01_title: "Desenhe a molécula",
    step_01_desc: "Use o editor químico 2D integrado para posicionar átomos e ligações, ou escolha do catálogo.",
    step_02_title: "Escolha um alvo",
    step_02_desc: "Selecione contra qual receptor de proteína deseja simular o acoplamento.",
    step_03_title: "Avalie e analise",
    step_03_desc: "Veja como seu computador avalia a estrutura em 10 níveis e emite um certificado inalterável.",
    stats_molecules: "Moléculas Avaliadas",
    stats_best_score: "Melhor Score (kcal/mol)",
    stats_certified: "Certificados Blockchain",

    opt_appearance: "Aparência",
    opt_theme: "Tema",
    opt_theme_dark: "Escuro",
    opt_theme_light: "Claro",
    opt_interface: "Interface",
    opt_sounds: "Sons da Interface",
    opt_sounds_muted: "Sons desativados",
    opt_sounds_active: "Sons ativos",
    opt_sounds_activate: "Clique para ativar",
    opt_sounds_silence: "Clique para desativar",
    opt_ai: "Intérprete de IA",
    opt_ai_config: "Configurar provedor de IA",
    opt_ai_chat_open: "Abrir MolChat",
    opt_ai_chat_close: "Fechar MolChat",
    opt_data: "Dados e Backup",
    opt_data_export: "Exportar Biblioteca (JSON)",
    opt_data_export_desc: "Baixe todas as suas moléculas e resultados em um arquivo portátil",
    opt_data_export_success: "Backup exportado com sucesso",
    opt_data_reset: "Redefinir dados da sessão",
    opt_data_reset_desc: "Encerra a sessão local ativa. O histórico de avaliações permanece no banco de dados.",
    opt_data_reset_warning: "Esta ação desconectará sua conta. Suas moléculas não serão excluídas.",
    opt_data_reset_success: "Sessão redefinida",
    opt_legal: "Legal e Info",
    opt_legal_terms: "Termos e Privacidade",
    opt_legal_about: "Sobre",

    legal_title: "Marco Legal — MolDesign AI",
    legal_tab_terms: "Termos de Uso",
    legal_tab_priv: "Privacidade",
    legal_tab_lic: "Licença",
    legal_local_first: "Local-First · Sem Telemetria · 100% Offline",
    legal_understood: "Entendido",

    login_title: "Login Local",
    login_subtitle: "MolDesign funciona 100% localmente no seu dispositivo.",
    login_username: "Nome de Usuário",
    login_password: "Senha (Mínimo 4 caracteres)",
    login_btn: "Acessar Laboratório",
    login_privacy_badge: "Seus dados nunca saem deste dispositivo.",
    login_error_fields: "Por favor, preencha todos os campos corretamente.",
    login_error_auth: "Credenciais incorretas.",

    eval_title: "Painel de Avaliação Molecular",
    eval_draw_tab: "1. Desenhar Molécula",
    eval_target_tab: "2. Selecionar Alvo",
    eval_run_tab: "3. Simulação e Score",
    eval_results_tab: "4. Relatório Final",
    eval_target_select_title: "Selecionar Alvo de Acoplamento",
    eval_target_desc: "Selecione contra qual receptor de proteína simular o acoplamento molecular (Docking).",
    eval_run_simulation: "Iniciar Simulação Científica",
    eval_docking_progress: "Simulando acoplamento molecular...",
    eval_docking_success: "Acoplamento molecular concluído com sucesso.",
    eval_docking_fail: "Erro durante a simulação de acoplamento.",
    eval_vina_score: "Afinidade Vina",
    eval_admet_score: "Propriedades ADMET",
    eval_solana_status: "Registro experimental na Solana",
    eval_solana_btn: "Testar registro na devnet",

    moldex_title: "Biblioteca de Alvos Moleculares (Moldex)",
    moldex_search: "Buscar alvo...",
    moldex_table_pdb: "ID PDB",
    moldex_table_name: "Nome do Receptor",
    moldex_table_type: "Tipo",
    moldex_table_resolution: "Resolução",
  },
  fr: {
    options: "Options",
    batch: "Lot",
    evaluation: "Évaluation",
    moldex: "Moldex",
    support: "Support",
    logout: "Se déconnecter",
    login: "Se connecter",
    welcome: "Bienvenue",
    close: "Fermer",
    save: "Sauvegarder",
    cancel: "Annuler",
    confirm: "Confirmer",
    error: "Erreur",
    success: "Succès",

    hero_tagline: "Laboratoire Académique",
    hero_title_1: "Concevez vos",
    hero_title_2: "propres",
    hero_title_3: "médicaments",
    hero_desc: "Apprenez étape par étape comment créer des molécules, évaluer leur viabilité et simuler leur interaction avec les récepteurs.",
    hero_button_edu: "Mode Étudiant",
    hero_button_pro: "Évaluation Avancée",
    features_title: "Flux de Travail Scientifique",
    step_01_title: "Dessiner la molécule",
    step_01_desc: "Utilisez l'éditeur chimique 2D intégré pour placer des liaisons et des atomes, ou choisissez dans le catalogue.",
    step_02_title: "Choisir une cible",
    step_02_desc: "Sélectionnez le récepteur protéique contre lequel simuler l'amarrage moléculaire.",
    step_03_title: "Évaluer et analyser",
    step_03_desc: "Regardez votre ordinateur évaluer la structure sur 10 niveaux et vous attribuer un certificat immuable.",
    stats_molecules: "Molécules Évaluées",
    stats_best_score: "Meilleur Score (kcal/mol)",
    stats_certified: "Certificats Blockchain",

    opt_appearance: "Apparence",
    opt_theme: "Thème",
    opt_theme_dark: "Sombre",
    opt_theme_light: "Clair",
    opt_interface: "Interface",
    opt_sounds: "Sons de l'Interface",
    opt_sounds_muted: "Sons désactivés",
    opt_sounds_active: "Sons activés",
    opt_sounds_activate: "Cliquer pour activer",
    opt_sounds_silence: "Cliquer pour désactiver",
    opt_ai: "Interprète IA",
    opt_ai_config: "Configurer le fournisseur IA",
    opt_ai_chat_open: "Ouvrir MolChat",
    opt_ai_chat_close: "Fermer MolChat",
    opt_data: "Données et Sauvegarde",
    opt_data_export: "Exporter la Bibliothèque (JSON)",
    opt_data_export_desc: "Téléchargez toutes vos molécules et résultats dans un fichier portable",
    opt_data_export_success: "Sauvegarde exportée avec succès",
    opt_data_reset: "Réinitialiser les données",
    opt_data_reset_desc: "Ferme la session locale active. L'historique d'évaluation reste dans la base de données.",
    opt_data_reset_warning: "Cette action va vous déconnecter. Vos molécules ne seront pas supprimées.",
    opt_data_reset_success: "Session réinitialisée",
    opt_legal: "Légal et Info",
    opt_legal_terms: "Conditions et Confidentialité",
    opt_legal_about: "À propos",

    legal_title: "Cadre Légal — MolDesign AI",
    legal_tab_terms: "Conditions d'Utilisation",
    legal_tab_priv: "Confidentialité",
    legal_tab_lic: "Licence",
    legal_local_first: "Local-First · Sans Télémétrie · 100% Offline",
    legal_understood: "Compris",

    login_title: "Connexion Locale",
    login_subtitle: "MolDesign fonctionne à 100% localement sur votre appareil.",
    login_username: "Nom d'utilisateur",
    login_password: "Mot de passe (Min 4 caractères)",
    login_btn: "Accéder au Laboratoire",
    login_privacy_badge: "Vos données ne quittent jamais cet appareil.",
    login_error_fields: "Veuillez remplir tous les champs correctement.",
    login_error_auth: "Identifiants incorrects.",

    eval_title: "Panneau d'Évaluation Moléculaire",
    eval_draw_tab: "1. Dessiner la Molécule",
    eval_target_tab: "2. Sélectionner la Cible",
    eval_run_tab: "3. Simulation & Score",
    eval_results_tab: "4. Rapport Final",
    eval_target_select_title: "Sélectionner la Cible d'Amarrage",
    eval_target_desc: "Sélectionnez le récepteur protéique contre lequel simuler l'amarrage moléculaire (Docking).",
    eval_run_simulation: "Démarrer la Simulation Scientifique",
    eval_docking_progress: "Simulation de l'amarrage moléculaire...",
    eval_docking_success: "Amarrage moléculaire réussi.",
    eval_docking_fail: "Erreur pendant la simulation d'amarrage.",
    eval_vina_score: "Affinité de Vina",
    eval_admet_score: "Propriétés ADMET",
    eval_solana_status: "Enregistrement Solana expérimental",
    eval_solana_btn: "Tester sur devnet",

    moldex_title: "Bibliothèque de Cibles Moléculaires (Moldex)",
    moldex_search: "Rechercher une cible...",
    moldex_table_pdb: "ID PDB",
    moldex_table_name: "Nom du Récepteur",
    moldex_table_type: "Type",
    moldex_table_resolution: "Résolution",
  },
  de: {
    options: "Optionen",
    batch: "Stapel",
    evaluation: "Bewertung",
    moldex: "Moldex",
    support: "Support",
    logout: "Abmelden",
    login: "Anmelden",
    welcome: "Willkommen",
    close: "Schließen",
    save: "Speichern",
    cancel: "Abbrechen",
    confirm: "Bestätigen",
    error: "Fehler",
    success: "Erfolg",

    hero_tagline: "Akademisches Labor",
    hero_title_1: "Entwerfe deine",
    hero_title_2: "eigenen",
    hero_title_3: "Medikamente",
    hero_desc: "Lerne Schritt für Schritt, wie man Moleküle erstellt, ihre Lebensfähigkeit bewertet und simuliert, wie sie mit Zellrezeptoren interagieren.",
    hero_button_edu: "Studentenmodus",
    hero_button_pro: "Erweiterte Bewertung",
    features_title: "Wissenschaftlicher Arbeitsablauf",
    step_01_title: "Molekül zeichnen",
    step_01_desc: "Nutze den integrierten 2D-Chemieditor, um Bindungen und Atome zu platzieren, oder wähle aus dem Katalog.",
    step_02_title: "Zielstruktur wählen",
    step_02_desc: "Wähle das Protein- oder Rezeptor-Ziel für das molekulare Docking aus.",
    step_03_title: "Bewerten und analysieren",
    step_03_desc: "Sieh zu, wie dein Computer die Struktur auf 10 Ebenen bewertet und dir ein fälschungssicheres Zertifikat ausstellt.",
    stats_molecules: "Evaluierte Moleküle",
    stats_best_score: "Bester Score (kcal/mol)",
    stats_certified: "Blockchain-Zertifikate",

    opt_appearance: "Aussehen",
    opt_theme: "Theme",
    opt_theme_dark: "Dunkel",
    opt_theme_light: "Hell",
    opt_interface: "Schnittstelle",
    opt_sounds: "Schnittstellentöne",
    opt_sounds_muted: "Töne stummgeschaltet",
    opt_sounds_active: "Töne aktiv",
    opt_sounds_activate: "Klicken zum Aktivieren",
    opt_sounds_silence: "Klicken zum Deaktivieren",
    opt_ai: "KI-Dolmetscher",
    opt_ai_config: "KI-Anbieter konfigurieren",
    opt_ai_chat_open: "MolChat öffnen",
    opt_ai_chat_close: "MolChat schließen",
    opt_data: "Daten & Backup",
    opt_data_export: "Bibliothek exportieren (JSON)",
    opt_data_export_desc: "Lade all deine Moleküle und Ergebnisse als portable Datei herunter",
    opt_data_export_success: "Backup erfolgreich exportiert",
    opt_data_reset: "Sitzungsdaten zurücksetzen",
    opt_data_reset_desc: "Schließt die aktive lokale Sitzung. Die Historie bleibt in der Datenbank erhalten.",
    opt_data_reset_warning: "Diese Aktion meldet dich ab. Deine Moleküle werden nicht gelöscht.",
    opt_data_reset_success: "Sitzung zurückgesetzt",
    opt_legal: "Rechtliches & Info",
    opt_legal_terms: "Nutzungsbedingungen & Datenschutz",
    opt_legal_about: "Über",

    legal_title: "Rechtlicher Rahmen — MolDesign AI",
    legal_tab_terms: "Nutzungsbedingungen",
    legal_tab_priv: "Datenschutz",
    legal_tab_lic: "Lizenz",
    legal_local_first: "Local-First · Keine Telemetrie · 100% Offline",
    legal_understood: "Verstanden",

    login_title: "Lokale Anmeldung",
    login_subtitle: "MolDesign läuft zu 100% lokal auf deinem Gerät.",
    login_username: "Benutzername",
    login_password: "Passwort (Min. 4 Zeichen)",
    login_btn: "Labor betreten",
    login_privacy_badge: "Deine Daten verlassen dieses Gerät niemals.",
    login_error_fields: "Bitte fülle alle Felder korrekt aus.",
    login_error_auth: "Falsche Anmeldedaten.",

    eval_title: "Molekulares Bewertungs-Panel",
    eval_draw_tab: "1. Molekül zeichnen",
    eval_target_tab: "2. Zielstruktur wählen",
    eval_run_tab: "3. Simulation & Score",
    eval_results_tab: "4. Abschlussbericht",
    eval_target_select_title: "Docking-Zielstruktur wählen",
    eval_target_desc: "Wähle aus, gegen welchen Proteinrezeptor das molekulare Docking simuliert werden soll.",
    eval_run_simulation: "Wissenschaftliche Simulation starten",
    eval_docking_progress: "Molekulares Docking wird simuliert...",
    eval_docking_success: "Molekulares Docking erfolgreich abgeschlossen.",
    eval_docking_fail: "Fehler während der Docking-Simulation.",
    eval_vina_score: "Vina-Affinität",
    eval_admet_score: "ADMET-Eigenschaften",
    eval_solana_status: "Experimenteller Solana-Eintrag",
    eval_solana_btn: "Devnet-Eintrag testen",

    moldex_title: "Molekulare Zieldatenbank (Moldex)",
    moldex_search: "Zielstruktur suchen...",
    moldex_table_pdb: "PDB-ID",
    moldex_table_name: "Rezeptorname",
    moldex_table_type: "Typ",
    moldex_table_resolution: "Auflösung",
  },
  it: {
    options: "Opzioni",
    batch: "Lotto",
    evaluation: "Valutazione",
    moldex: "Moldex",
    support: "Supporto",
    logout: "Esci",
    login: "Accedi",
    welcome: "Benvenuto",
    close: "Chiudi",
    save: "Salva",
    cancel: "Annulla",
    confirm: "Conferma",
    error: "Errore",
    success: "Successo",

    hero_tagline: "Laboratorio Accademico",
    hero_title_1: "Progetta i tuoi",
    hero_title_2: "recettori",
    hero_title_3: "farmaci",
    hero_desc: "Impara passo dopo passo come creare molecole, valutarne la fattibilità e simulare l'interazione con i recettori cellulari.",
    hero_button_edu: "Modalità Studente",
    hero_button_pro: "Valutazione Avanzata",
    features_title: "Flusso di Lavoro Scientifico",
    step_01_title: "Disegna la molecola",
    step_01_desc: "Usa l'editor chimico 2D integrato per posizionare legami e atomi, o seleziona dal catalogo.",
    step_02_title: "Scegli un bersaglio",
    step_02_desc: "Seleziona contro quale recettore proteico simulare l'attracco molecolare.",
    step_03_title: "Valuta e analizza",
    step_03_desc: "Guarda come il tuo computer valuta la struttura su 10 livelli e ti assegna un certificato immutabile.",
    stats_molecules: "Molecole Valutate",
    stats_best_score: "Miglior Score (kcal/mol)",
    stats_certified: "Certificati Blockchain",

    opt_appearance: "Aspetto",
    opt_theme: "Tema",
    opt_theme_dark: "Scuro",
    opt_theme_light: "Chiaro",
    opt_interface: "Interfaccia",
    opt_sounds: "Suoni dell'Interfaccia",
    opt_sounds_muted: "Suoni disattivati",
    opt_sounds_active: "Suoni attivi",
    opt_sounds_activate: "Clicca per attivare",
    opt_sounds_silence: "Clicca per disattivare",
    opt_ai: "Interprete IA",
    opt_ai_config: "Configura provider IA",
    opt_ai_chat_open: "Apri MolChat",
    opt_ai_chat_close: "Chiudi MolChat",
    opt_data: "Dati & Backup",
    opt_data_export: "Esporta Libreria (JSON)",
    opt_data_export_desc: "Scarica tutte le tue molecole e i risultati in un file portatile",
    opt_data_export_success: "Backup esportato correttamente",
    opt_data_reset: "Ripristina i dati",
    opt_data_reset_desc: "Chiude la sessione locale attiva. La cronologia delle valutazioni rimane nel database.",
    opt_data_reset_warning: "Questa azione ti disconnetterà. Le tue molecole non verranno eliminate.",
    opt_data_reset_success: "Sessione ripristinata",
    opt_legal: "Legale e Info",
    opt_legal_terms: "Termini e Privacy",
    opt_legal_about: "Informazioni su",

    legal_title: "Quadro Legale — MolDesign AI",
    legal_tab_terms: "Termini di Utilizzo",
    legal_tab_priv: "Privacy",
    legal_tab_lic: "Licenza",
    legal_local_first: "Local-First · Nessuna Telemetria · 100% Offline",
    legal_understood: "Capito",

    login_title: "Accesso Locale",
    login_subtitle: "MolDesign funziona al 100% localmente sul tuo dispositivo.",
    login_username: "Nome Utente",
    login_password: "Password (Minimo 4 caratteri)",
    login_btn: "Accedi al Laboratorio",
    login_privacy_badge: "I tuoi dati non lasciano mai questo dispositivo.",
    login_error_fields: "Per favore, compila tutti i campi correttamente.",
    login_error_auth: "Credenziali non corrette.",

    eval_title: "Pannello di Valutazione Molecolare",
    eval_draw_tab: "1. Disegna Molecola",
    eval_target_tab: "2. Seleziona Bersaglio",
    eval_run_tab: "3. Simulazione & Score",
    eval_results_tab: "4. Rapporto Finale",
    eval_target_select_title: "Seleziona Bersaglio di Attracco",
    eval_target_desc: "Seleziona contro quale recettore proteico simulare l'attracco molecolare (Docking).",
    eval_run_simulation: "Avvia Simulazione Scientifica",
    eval_docking_progress: "Simulazione dell'attracco molecolare...",
    eval_docking_success: "Attracco molecolare completato con successo.",
    eval_docking_fail: "Errore durante la simulazione di attracco.",
    eval_vina_score: "Affinità Vina",
    eval_admet_score: "Proprietà ADMET",
    eval_solana_status: "Registrazione Solana sperimentale",
    eval_solana_btn: "Prova su devnet",

    moldex_title: "Libreria dei Bersagli Molecolari (Moldex)",
    moldex_search: "Cerca bersaglio...",
    moldex_table_pdb: "ID PDB",
    moldex_table_name: "Nome del Recettore",
    moldex_table_type: "Tipo",
    moldex_table_resolution: "Risoluzione",
  },
  zh: {
    options: "选项",
    batch: "批处理",
    evaluation: "评估",
    moldex: "靶点库",
    support: "支持",
    logout: "退出登录",
    login: "登录",
    welcome: "欢迎",
    close: "关闭",
    save: "保存",
    cancel: "取消",
    confirm: "确认",
    error: "错误",
    success: "成功",

    hero_tagline: "学术实验室",
    hero_title_1: "设计你自己的",
    hero_title_2: "专属",
    hero_title_3: "药物",
    hero_desc: "逐步学习如何创建分子、评估其可行性，并模拟它们如何与细胞受体相互作用。",
    hero_button_edu: "学生模式",
    hero_button_pro: "高级评估",
    features_title: "科学工作流程",
    step_01_title: "绘制分子",
    step_01_desc: "使用集成的2D化学编辑器放置化学键和原子，或从目录中选择已知药物。",
    step_02_title: "选择靶点",
    step_02_desc: "选择您想要进行分子对接模拟的蛋白质受体。",
    step_03_title: "评估与分析",
    step_03_desc: "观察您的计算机如何在10个维度上评估分子结构，并为您生成不可篡改的区块链证书。",
    stats_molecules: "已评估分子数",
    stats_best_score: "最佳亲和力 (kcal/mol)",
    stats_certified: "区块链证书数",

    opt_appearance: "外观",
    opt_theme: "主题",
    opt_theme_dark: "暗色",
    opt_theme_light: "亮色",
    opt_interface: "界面模式",
    opt_sounds: "界面音效",
    opt_sounds_muted: "静音",
    opt_sounds_active: "开启音效",
    opt_sounds_activate: "点击开启",
    opt_sounds_silence: "点击静音",
    opt_ai: "AI 解释器",
    opt_ai_config: "配置 AI 服务商",
    opt_ai_chat_open: "开启 MolChat",
    opt_ai_chat_close: "关闭 MolChat",
    opt_data: "数据与备份",
    opt_data_export: "导出本地数据库 (JSON)",
    opt_data_export_desc: "下载您所有的分子及评估结果至便携式文件",
    opt_data_export_success: "备份导出成功",
    opt_data_reset: "重置会话数据",
    opt_data_reset_desc: "清除本地会话。评估历史数据仍保留在数据库中。",
    opt_data_reset_warning: "此操作将注销会话。您的分子数据不会被删除。",
    opt_data_reset_success: "会话已重置",
    opt_legal: "法律与信息",
    opt_legal_terms: "条款与隐私政策",
    opt_legal_about: "关于",

    legal_title: "法律框架 — MolDesign AI",
    legal_tab_terms: "使用条款",
    legal_tab_priv: "隐私政策",
    legal_tab_lic: "开源许可证",
    legal_local_first: "本地优先 · 无遥测 · 100% 离线运行",
    legal_understood: "我知道了",

    login_title: "本地会话登录",
    login_subtitle: "MolDesign 在您的设备上 100% 离线本地运行。",
    login_username: "用户名",
    login_password: "密码 (至少4位字符)",
    login_btn: "进入实验室",
    login_privacy_badge: "您的数据绝不会离开此设备。",
    login_error_fields: "请正确填写所有字段。",
    login_error_auth: "用户名或密码错误。",

    eval_title: "分子评估面板",
    eval_draw_tab: "1. 绘制分子",
    eval_target_tab: "2. 选择靶点",
    eval_run_tab: "3. 模拟与评分",
    eval_results_tab: "4. 最终报告",
    eval_target_select_title: "选择对接靶点",
    eval_target_desc: "选择用于模拟分子对接 (Docking) 的目标蛋白质受体。",
    eval_run_simulation: "开始科学模拟",
    eval_docking_progress: "分子对接模拟中...",
    eval_docking_success: "分子对接模拟成功完成。",
    eval_docking_fail: "对接模拟过程中发生错误。",
    eval_vina_score: "Vina 亲和力",
    eval_admet_score: "ADMET 属性评分",
    eval_solana_status: "Solana 开发网实验记录",
    eval_solana_btn: "测试开发网记录",

    moldex_title: "分子靶点库 (Moldex)",
    moldex_search: "搜索靶点...",
    moldex_table_pdb: "PDB 编号",
    moldex_table_name: "受体名称",
    moldex_table_type: "类型",
    moldex_table_resolution: "分辨率",
  },
  ja: {
    options: "オプション",
    batch: "一括処理",
    evaluation: "評価実行",
    moldex: "標的ライブラリ",
    support: "サポート",
    logout: "ログアウト",
    login: "ログイン",
    welcome: "ようこそ",
    close: "閉じる",
    save: "保存",
    cancel: "キャンセル",
    confirm: "確定",
    error: "エラー",
    success: "成功",

    hero_tagline: "学術研究室",
    hero_title_1: "独自の",
    hero_title_2: "医薬品を",
    hero_title_3: "設計する",
    hero_desc: "分子の作成方法、その生存可能性の評価、cell受容体との相互作用シミュレーションを段階的に学びます。",
    hero_button_edu: "学生モード",
    hero_button_pro: "高度な評価",
    features_title: "科学的ワークフロー",
    step_01_title: "分子を描画",
    step_01_desc: "統合された2D化学エディターを使用して結合と原子を配置するか、既知の薬を選択します。",
    step_02_title: "標的を選択",
    step_02_desc: "ドッキングシミュレーションの対象となるタンパク質受容体を選択します。",
    step_03_title: "評価と解析",
    step_03_desc: "コンピューターが構造を10段階で評価し、ブロックチェーン証明書を発行する様子を確認します。",
    stats_molecules: "評価済み分子数",
    stats_best_score: "最高スコア (kcal/mol)",
    stats_certified: "ブロックチェーン証明書",

    opt_appearance: "外観",
    opt_theme: "テーマ",
    opt_theme_dark: "ダーク",
    opt_theme_light: "ライト",
    opt_interface: "インターフェース",
    opt_sounds: "システム音效",
    opt_sounds_muted: "消音",
    opt_sounds_active: "音效有効",
    opt_sounds_activate: "クリックで有効化",
    opt_sounds_silence: "クリックで消音",
    opt_ai: "AI インタプリタ",
    opt_ai_config: "AIプロバイダー設定",
    opt_ai_chat_open: "MolChatを開く",
    opt_ai_chat_close: "MolChatを閉じる",
    opt_data: "データとバックアップ",
    opt_data_export: "ライブラリをエクスポート (JSON)",
    opt_data_export_desc: "すべての分子と結果をポータブルファイルとしてダウンロードします",
    opt_data_export_success: "バックアップを正常に書き出しました",
    opt_data_reset: "セッションデータの初期化",
    opt_data_reset_desc: "現在のローカルセッションを閉じます。評価履歴はデータベースに残ります。",
    opt_data_reset_warning: "この操作によりログアウトされます。分子データは削除されません。",
    opt_data_reset_success: "セッションをリセットしました",
    opt_legal: "法的情報",
    opt_legal_terms: "利用規約とプライバシー",
    opt_legal_about: "バージョン情報",

    legal_title: "法的枠組み — MolDesign AI",
    legal_tab_terms: "利用規約",
    legal_tab_priv: "プライバシーポリシー",
    legal_tab_lic: "ライセンス",
    legal_local_first: "ローカルファースト · 追跡なし · 100% オフライン",
    legal_understood: "了解",

    login_title: "ローカルログイン",
    login_subtitle: "MolDesignはデバイス上で100%ローカルに動作します。",
    login_username: "ユーザー名",
    login_password: "パスワード (4文字以上)",
    login_btn: "研究室に入る",
    login_privacy_badge: "データがデバイスの外へ送信されることはありません。",
    login_error_fields: "すべてのフィールドを正しく入力してください。",
    login_error_auth: "ログイン情報が正しくありません。",

    eval_title: "分子評価パネル",
    eval_draw_tab: "1. 分子描画",
    eval_target_tab: "2. 標的選択",
    eval_run_tab: "3. シミュレーション実行",
    eval_results_tab: "4. 最終レポート",
    eval_target_select_title: "ドッキング標的の選択",
    eval_target_desc: "分子ドッキング（Docking）を行うタンパク質受容体を選択します。",
    eval_run_simulation: "シミュレーション開始",
    eval_docking_progress: "ドッキングシミュレーションを実行中...",
    eval_docking_success: "ドッキングシミュレーションが完了しました。",
    eval_docking_fail: "シミュレーション中にエラーが発生しました。",
    eval_vina_score: "Vina 結合親和性",
    eval_admet_score: "ADMET特性評価",
    eval_solana_status: "Solana devnet実験記録",
    eval_solana_btn: "devnet記録を試す",

    moldex_title: "標的受容体ライブラリ (Moldex)",
    moldex_search: "標的を検索...",
    moldex_table_pdb: "PDB ID",
    moldex_table_name: "受容体名",
    moldex_table_type: "タイプ",
    moldex_table_resolution: "解像度",
  },
  ko: {
    options: "옵션",
    batch: "일괄 처리",
    evaluation: "평가 수행",
    moldex: "표적 라이브러리",
    support: "지원",
    logout: "로그아웃",
    login: "로그인",
    welcome: "환영합니다",
    close: "닫기",
    save: "저장",
    cancel: "취소",
    confirm: "확인",
    error: "오류",
    success: "성공",

    hero_tagline: "학술 연구소",
    hero_title_1: "나만의",
    hero_title_2: "의약품을",
    hero_title_3: "설계하다",
    hero_desc: "분자를 생성하고, 생존 가능성을 평가하며, 세포 수용체와 상호 작용하는 방법을 단계별로 시뮬레이션합니다.",
    hero_button_edu: "학생 모드",
    hero_button_pro: "고급 평가 모드",
    features_title: "과학적 워크플로우",
    step_01_title: "분자 그리기",
    step_01_desc: "통합된 2D 화학 편집기를 사용하여 결합과 원자를 배치하거나 기성 약물을 선택하십시오.",
    step_02_title: "표적 선택",
    step_02_desc: "도킹 시뮬레이션을 수행할 단백질 수용체를 선택하십시오.",
    step_03_title: "평가 및 분석",
    step_03_desc: "컴퓨터가 구조를 10가지 수준에서 평가하고 블록체인 인증서를 발급하는 과정을 관찰합니다.",
    stats_molecules: "평가된 분자 수",
    stats_best_score: "최고 점수 (kcal/mol)",
    stats_certified: "블록체인 인증서",

    opt_appearance: "테마 설정",
    opt_theme: "테마",
    opt_theme_dark: "어둡게",
    opt_theme_light: "밝게",
    opt_interface: "인터페이스",
    opt_sounds: "효과음 설정",
    opt_sounds_muted: "음소거됨",
    opt_sounds_active: "효과음 켬",
    opt_sounds_activate: "클릭하여 켜기",
    opt_sounds_silence: "클릭하여 음소거",
    opt_ai: "AI 인터프리터",
    opt_ai_config: "AI 제공자 설정",
    opt_ai_chat_open: "MolChat 열기",
    opt_ai_chat_close: "MolChat 닫기",
    opt_data: "데이터 및 백업",
    opt_data_export: "라이브러리 내보내기 (JSON)",
    opt_data_export_desc: "모든 분자 및 평가 데이터를 파일로 다운로드합니다.",
    opt_data_export_success: "백업을 성공적으로 내보냈습니다",
    opt_data_reset: "세션 데이터 초기화",
    opt_data_reset_desc: "현재 로컬 세션을 닫습니다. 데이터베이스의 평가 기록은 유지됩니다.",
    opt_data_reset_warning: "이 작업은 로그아웃을 수행합니다. 분자 데이터는 삭제되지 않습니다.",
    opt_data_reset_success: "세션이 초기화되었습니다",
    opt_legal: "법적 고지",
    opt_legal_terms: "이용 약관 및 개인정보",
    opt_legal_about: "제품 정보",

    legal_title: "법적 프레임워크 — MolDesign AI",
    legal_tab_terms: "이용 약관",
    legal_tab_priv: "개인정보 처리방침",
    legal_tab_lic: "라이선스",
    legal_local_first: "로컬 퍼스트 · 추적 없음 · 100% 오프라인 작동",
    legal_understood: "확인함",

    login_title: "로컬 로그인",
    login_subtitle: "MolDesign은 기기에서 100% 로컬로 동작합니다.",
    login_username: "사용자 이름",
    login_password: "비밀번호 (4자 이상)",
    login_btn: "연구실 입장",
    login_privacy_badge: "사용자 데이터는 절대 외부로 유출되지 않습니다.",
    login_error_fields: "모든 필드를 올바르게 입력하십시오.",
    login_error_auth: "로그인 정보가 일치하지 않습니다.",

    eval_title: "분자 평가 패널",
    eval_draw_tab: "1. 분자 그리기",
    eval_target_tab: "2. 표적 선택",
    eval_run_tab: "3. 시뮬레이션 실행",
    eval_results_tab: "4. 최종 보고서",
    eval_target_select_title: "도킹 표적 선택",
    eval_target_desc: "분자 도킹(Docking)을 수행할 단백질 수용체를 선택합니다.",
    eval_run_simulation: "과학적 시뮬레이션 시작",
    eval_docking_progress: "분자 도킹 시뮬레이션 중...",
    eval_docking_success: "분자 도킹 시뮬레이션이 성공적으로 완료되었습니다.",
    eval_docking_fail: "시뮬레이션 수행 중 오류가 발생했습니다.",
    eval_vina_score: "Vina 결합 친화도",
    eval_admet_score: "ADMET 성질 평가",
    eval_solana_status: "Solana devnet 실험 기록",
    eval_solana_btn: "devnet 기록 시험",

    moldex_title: "표적 단백질 라이브러리 (Moldex)",
    moldex_search: "표적 검색...",
    moldex_table_pdb: "PDB ID",
    moldex_table_name: "수용체 이름",
    moldex_table_type: "유형",
    moldex_table_resolution: "해상도",
  },
  ru: {
    options: "Опции",
    batch: "Пакет",
    evaluation: "Оценка",
    moldex: "Мишени",
    support: "Поддержка",
    logout: "Выйти",
    login: "Войти",
    welcome: "Добро пожаловать",
    close: "Закрыть",
    save: "Сохранить",
    cancel: "Отмена",
    confirm: "Подтвердить",
    error: "Ошибка",
    success: "Успех",

    hero_tagline: "Академическая лаборатория",
    hero_title_1: "Создавайте свои",
    hero_title_2: "собственные",
    hero_title_3: "лекарства",
    hero_desc: "Изучите шаг за шагом, как создавать молекулы, оценивать их жизнеспособность и симулировать их взаимодействие с клеточными рецепторами.",
    hero_button_edu: "Режим студента",
    hero_button_pro: "Продвинутый анализ",
    features_title: "Научный процесс",
    step_01_title: "Нарисуйте молекулу",
    step_01_desc: "Используйте встроенный 2D химический редактор, чтобы расставлять связи и атомы, или выберите из каталога.",
    step_02_title: "Выберите мишень",
    step_02_desc: "Выберите, с каким белковым рецептором симулировать молекулярный докинг.",
    step_03_title: "Оцените и проанализируйте",
    step_03_desc: "Наблюдайте, как компьютер оценивает структуру по 10 уровням и выдает вам блокчейн-сертификат.",
    stats_molecules: "Оцененные молекулы",
    stats_best_score: "Лучший результат (ккал/моль)",
    stats_certified: "Блокчейн-сертификаты",

    opt_appearance: "Внешний вид",
    opt_theme: "Тема",
    opt_theme_dark: "Темная",
    opt_theme_light: "Светлая",
    opt_interface: "Интерфейс",
    opt_sounds: "Звуки интерфейса",
    opt_sounds_muted: "Звуки отключены",
    opt_sounds_active: "Звуки включены",
    opt_sounds_activate: "Нажмите, чтобы включить",
    opt_sounds_silence: "Нажмите, чтобы отключить",
    opt_ai: "ИИ-Интерпретатор",
    opt_ai_config: "Настройка ИИ-провайдера",
    opt_ai_chat_open: "Открыть MolChat",
    opt_ai_chat_close: "Закрыть MolChat",
    opt_data: "Данные и Резервное копирование",
    opt_data_export: "Экспорт библиотеки (JSON)",
    opt_data_export_desc: "Скачать ваши молекулы и результаты в виде переносимого файла",
    opt_data_export_success: "Резервная копия успешно экспортирована",
    opt_data_reset: "Сбросить данные сессии",
    opt_data_reset_desc: "Закрывает активную локальную сессию. История оценок остается в базе данных.",
    opt_data_reset_warning: "Это действие выйдет из системы. Ваши молекулы не будут удалены.",
    opt_data_reset_success: "Сессия успешно сброшена",
    opt_legal: "Юридическая информация",
    opt_legal_terms: "Условия использования и конфиденциальность",
    opt_legal_about: "О программе",

    legal_title: "Юридические рамки — MolDesign AI",
    legal_tab_terms: "Условия использования",
    legal_tab_priv: "Конфиденциальность",
    legal_tab_lic: "Лицензия",
    legal_local_first: "Local-First · Без телеметрии · 100% Offline",
    legal_understood: "Понятно",

    login_title: "Локальный вход",
    login_subtitle: "MolDesign работает на 100% локально на вашем устройстве.",
    login_username: "Имя пользователя",
    login_password: "Пароль (минимум 4 символа)",
    login_btn: "Войти в лабораторию",
    login_privacy_badge: "Ваши данные никогда не покидают это устройство.",
    login_error_fields: "Пожалуйста, заполните все поля корректно.",
    login_error_auth: "Неверные учетные данные.",

    eval_title: "Панель молекулярной оценки",
    eval_draw_tab: "1. Рисование молекулы",
    eval_target_tab: "2. Выбор мишени",
    eval_run_tab: "3. Симуляция и Результат",
    eval_results_tab: "4. Отчет",
    eval_target_select_title: "Выбор мишени для докинга",
    eval_target_desc: "Выберите, против какого белкового рецептора симулировать молекулярный докинг.",
    eval_run_simulation: "Запустить научную симуляцию",
    eval_docking_progress: "Симуляция молекулярного докинга...",
    eval_docking_success: "Молекулярный докинг успешно завершен.",
    eval_docking_fail: "Ошибка во время симуляции докинга.",
    eval_vina_score: "Аффинность Vina",
    eval_admet_score: "Свойства ADMET",
    eval_solana_status: "Экспериментальная запись Solana",
    eval_solana_btn: "Проверить запись в devnet",

    moldex_title: "Библиотека белковых мишеней (Moldex)",
    moldex_search: "Поиск мишени...",
    moldex_table_pdb: "PDB ID",
    moldex_table_name: "Название рецептора",
    moldex_table_type: "Тип",
    moldex_table_resolution: "Разрешение",
  },
  hi: {
    options: "विकल्प",
    batch: "बैच",
    evaluation: "मूल्यांकन",
    moldex: "मोल्डेक्स",
    support: "सहायता",
    logout: "लॉग आउट",
    login: "लॉग इन",
    welcome: "स्वागत है",
    close: "बंद करें",
    save: "सहेजें",
    cancel: "रद्द करें",
    confirm: "पुष्टि करें",
    error: "त्रुटि",
    success: "सफलता",

    hero_tagline: "अकादमिक प्रयोगशाला",
    hero_title_1: "अपनी खुद की",
    hero_title_2: "दवाएं",
    hero_title_3: "डिजाइन करें",
    hero_desc: "चरण-दर-चरण सीखें कि अणु कैसे बनाएं, उनकी व्यवहार्यता का आकलन कैसे करें, और सेलुलर रिसेप्टर्स के साथ वे कैसे बातचीत करते हैं इसका अनुकरण करें।",
    hero_button_edu: "छात्र मोड",
    hero_button_pro: "उन्नत मूल्यांकन",
    features_title: "वैज्ञानिक कार्यप्रवाह",
    step_01_title: "अणु बनाएं",
    step_01_desc: "बॉन्ड और परमाणुओं को रखने के लिए एकीकृत 2D रासायनिक संपादक का उपयोग करें, या सूची से एक ज्ञात दवा चुनें।",
    step_02_title: "लक्ष्य चुनें",
    step_02_desc: "चुनें कि आप किस प्रोटीन या जैविक रिसेप्टर के खिलाफ डॉक करना चाहते हैं।",
    step_03_title: "मूल्यांकन और विश्लेषण",
    step_03_desc: "देखें कि आपका कंप्यूटर 10 स्तरों में संरचना का मूल्यांकन कैसे करता है और आपको ब्लॉकचेन प्रमाणपत्र देता है।",
    stats_molecules: "मूल्यांकित अणु",
    stats_best_score: "सर्वश्रेष्ठ स्कोर (kcal/mol)",
    stats_certified: "ब्लॉकचेन प्रमाणपत्र",

    opt_appearance: "दिखावट",
    opt_theme: "थीम",
    opt_theme_dark: "डार्क",
    opt_theme_light: "लाइट",
    opt_interface: "इंटरफ़ेस मोड",
    opt_sounds: "इंटरफ़ेस ध्वनियाँ",
    opt_sounds_muted: "मौन",
    opt_sounds_active: "सक्रिय",
    opt_sounds_activate: "सक्रिय करने के लिए क्लिक करें",
    opt_sounds_silence: "मौन करने के लिए क्लिक करें",
    opt_ai: "एआई दुभाषिया",
    opt_ai_config: "एआई प्रदाता सेट करें",
    opt_ai_chat_open: "MolChat खोलें",
    opt_ai_chat_close: "MolChat बंद करें",
    opt_data: "डेटा और बैकअप",
    opt_data_export: "लाइब्रेरी निर्यात करें (JSON)",
    opt_data_export_desc: "अपने सभी अणुओं और परिणामों को एक पोर्टेबल फ़ाइल में डाउनलोड करें",
    opt_data_export_success: "बैकअप सफलतापूर्वक निर्यात किया गया",
    opt_data_reset: "सत्र डेटा रीसेट करें",
    opt_data_reset_desc: "सक्रिय स्थानीय सत्र बंद करें। डेटाबेस में मूल्यांकन इतिहास सुरक्षित रहता है।",
    opt_data_reset_warning: "यह क्रिया आपको लॉग आउट कर देगी। आपके अणु हटाए नहीं जाएंगे।",
    opt_data_reset_success: "सत्र रीसेट हो गया",
    opt_legal: "कानूनी और जानकारी",
    opt_legal_terms: "नियम और गोपनीयता",
    opt_legal_about: "के बारे में",

    legal_title: "कानूनी ढांचा — MolDesign AI",
    legal_tab_terms: "उपयोग की शर्तें",
    legal_tab_priv: "गोपनीयता नीति",
    legal_tab_lic: "लाइसेंस",
    legal_local_first: "Local-First · कोई टेलीमेट्री नहीं · 100% ऑफ़लाइन",
    legal_understood: "समझ गया",

    login_title: "स्थानीय लॉगिन",
    login_subtitle: "MolDesign आपके डिवाइस पर 100% स्थानीय रूप से काम करता है।",
    login_username: "उपयोगकर्ता नाम",
    login_password: "पासवर्ड (न्यूनतम 4 वर्ण)",
    login_btn: "प्रयोगशाला में प्रवेश करें",
    login_privacy_badge: "आपका डेटा इस डिवाइस से बाहर नहीं जाता है।",
    login_error_fields: "कृपया सभी फ़ील्ड सही ढंग से भरें।",
    login_error_auth: "गलत क्रेडेंशियल।",

    eval_title: "आणविक मूल्यांकन पैनल",
    eval_draw_tab: "1. अणु आरेखित करें",
    eval_target_tab: "2. लक्ष्य चुनें",
    eval_run_tab: "3. सिमुलेशन और स्कोर",
    eval_results_tab: "4. अंतिम रिपोर्ट",
    eval_target_select_title: "डॉकिंग लक्ष्य का चयन करें",
    eval_target_desc: "चुनें कि किस प्रोटीन रिसेप्टर के खिलाफ आणविक डॉकिंग (Docking) का अनुकरण किया जाए।",
    eval_run_simulation: "वैज्ञानिक सिमुलेशन शुरू करें",
    eval_docking_progress: "आणविक डॉकिंग का अनुकरण कर रहा है...",
    eval_docking_success: "आणविक डॉकिंग सफलतापूर्वक पूरा हुआ।",
    eval_docking_fail: "डॉकिंग सिमुलेशन के दौरान त्रुटि।",
    eval_vina_score: "विना आत्मीयता",
    eval_admet_score: "ADMET गुण स्कोर",
    eval_solana_status: "प्रायोगिक Solana devnet रिकॉर्ड",
    eval_solana_btn: "devnet रिकॉर्ड आज़माएँ",

    moldex_title: "आणविक लक्ष्य लाइब्रेरी (Moldex)",
    moldex_search: "लक्ष्य खोजें...",
    moldex_table_pdb: "PDB आईडी",
    moldex_table_name: "रिसेप्टर का नाम",
    moldex_table_type: "प्रकार",
    moldex_table_resolution: "संकल्प",
  },
  ar: {
    options: "خيارات",
    batch: "دفعة",
    evaluation: "التقييم",
    moldex: "مولديكس",
    support: "الدعم",
    logout: "تسجيل الخروج",
    login: "تسجيل الدخول",
    welcome: "مرحباً",
    close: "إغلاق",
    save: "حفظ",
    cancel: "إلغاء",
    confirm: "تأكيد",
    error: "خطأ",
    success: "نجاح",

    hero_tagline: "مختبر أكاديمي",
    hero_title_1: "صمم أدويتك",
    hero_title_2: "الخاصة",
    hero_title_3: "بنفسك",
    hero_desc: "تعلم خطوة بخطوة كيفية إنشاء الجزيئات، وتقييم مدى فعاليتها، ومحاكاة كيفية تفاعلها مع المستقبيلات الخلوية.",
    hero_button_edu: "وضع الطالب",
    hero_button_pro: "التقييم المتقدم",
    features_title: "سير العمل العلمي",
    step_01_title: "ارسم الجزيء",
    step_01_desc: "استخدم المحرر الكيميائي ثنائي الأبعاد المدمج لوضع الروابط والذرات، أو اختر عقاراً معروفاً من الدليل.",
    step_02_title: "اختر الهدف",
    step_02_desc: "اختر مستقبل البروتين أو المستقبل البيولوجي الذي ترغب في محاكاة الارتباط به.",
    step_03_title: "قيّم وحلّل",
    step_03_desc: "شاهد كيف يقوم جهازك بتقييم الهيكل عبر 10 مستويات ويمنحك شهادة غير قابلة للتغيير في البلوكشين.",
    stats_molecules: "الجزيئات المقيمة",
    stats_best_score: "أفضل نتيجة (كيلو كالوري/مول)",
    stats_certified: "شهادات البلوكشين",

    opt_appearance: "المظهر",
    opt_theme: "المظهر",
    opt_theme_dark: "داكن",
    opt_theme_light: "فاتح",
    opt_interface: "وضع الواجهة",
    opt_sounds: "أصوات الواجهة",
    opt_sounds_muted: "الأصوات كتم",
    opt_sounds_active: "الأصوات نشطة",
    opt_sounds_activate: "انقر للتنشيط",
    opt_sounds_silence: "انقر للكتم",
    opt_ai: "مفسر الذكاء الاصطناعي",
    opt_ai_config: "إعداد موفر الذكاء الاصطناعي",
    opt_ai_chat_open: "فتح MolChat",
    opt_ai_chat_close: "إغلاق MolChat",
    opt_data: "البيانات والنسخ الاحتياطي",
    opt_data_export: "تصدير المكتبة (JSON)",
    opt_data_export_desc: "قم بتنزيل جميع جزيئاتك ونتائجك في ملف محمول",
    opt_data_export_success: "تم تصدير النسخة الاحتياطية بنجاح",
    opt_data_reset: "إعادة تعيين بيانات الجلسة",
    opt_data_reset_desc: "يغلق الجلسة المحلية النشطة. يظل سجل التقييم في قاعدة البيانات.",
    opt_data_reset_warning: "هذا الإجراء سيقوم بتسجيل خروجك. لن يتم حذف جزيئاتك.",
    opt_data_reset_success: "تمت إعادة تعيين الجلسة",
    opt_legal: "قانوني ومعلومات",
    opt_legal_terms: "الشروط والخصوصية",
    opt_legal_about: "حول",

    legal_title: "الإطار القانوني — MolDesign AI",
    legal_tab_terms: "شروط الاستخدام",
    legal_tab_priv: "سياسة الخصوصية",
    legal_tab_lic: "الترخيص",
    legal_local_first: "Local-First · بدون تتبع · 100% دون اتصال",
    legal_understood: "مفهوم",

    login_title: "تسجيل الدخول المحلي",
    login_subtitle: "يعمل MolDesign محلياً بنسبة 100% على جهازك.",
    login_username: "اسم المستخدم",
    login_password: "كلمة المرور (4 أحرف على الأقل)",
    login_btn: "الدخول إلى المختبر",
    login_privacy_badge: "بياناتك لا تغادر هذا الجهاز أبداً.",
    login_error_fields: "يرجى تعبئة جميع الحقول بشكل صحيح.",
    login_error_auth: "بيانات الاعتماد غير صحيحة.",

    eval_title: "لوحة تقييم الجزيئات",
    eval_draw_tab: "1. رسم الجزيء",
    eval_target_tab: "2. اختيار الهدف",
    eval_run_tab: "3. المحاكاة والنتيجة",
    eval_results_tab: "4. التقرير النهائي",
    eval_target_select_title: "اختر هدف الارتباط",
    eval_target_desc: "اختر مستقبل البروتين المراد محاكاة الارتباط الجزيئي (Docking) ضده.",
    eval_run_simulation: "بدء المحاكاة العلمية",
    eval_docking_progress: "محاكاة الارتباط الجزيئي...",
    eval_docking_success: "تم إكمال الارتباط الجزيئي بنجاح.",
    eval_docking_fail: "خطأ أثناء محاكاة الارتباط الجزيئي.",
    eval_vina_score: "إلفة فينا",
    eval_admet_score: "خصائص ADMET",
    eval_solana_status: "سجل Solana تجريبي",
    eval_solana_btn: "اختبار سجل devnet",

    moldex_title: "مكتبة الأهداف الجزيئية (Moldex)",
    moldex_search: "البحث عن هدف...",
    moldex_table_pdb: "معرف PDB",
    moldex_table_name: "اسم المستقبل",
    moldex_table_type: "النوع",
    moldex_table_resolution: "الدقة",
  },
  tr: {
    options: "Seçenekler",
    batch: "Toplu",
    evaluation: "Değerlendirme",
    moldex: "Moldex",
    support: "Destek",
    logout: "Çıkış Yap",
    login: "Giriş Yap",
    welcome: "Hoş geldiniz",
    close: "Kapat",
    save: "Kaydet",
    cancel: "İptal",
    confirm: "Onayla",
    error: "Hata",
    success: "Başarılı",

    hero_tagline: "Akademik Laboratuvar",
    hero_title_1: "Kendi ilaçlarınızı",
    hero_title_2: "kendiniz",
    hero_title_3: "tasarlayın",
    hero_desc: "Adım adım moleküller oluşturmayı, bunların uygulanabilirliğini değerlendirmeyi ve hücresel reseptörlerle nasıl etkileşime girdiklerini simüle etmeyi öğrenin.",
    hero_button_edu: "Öğrenci Modu",
    hero_button_pro: "Gelişmiş Değerlendirme",
    features_title: "Bilimsel İş Akışı",
    step_01_title: "Molekülü çizin",
    step_01_desc: "Bağlar ve atomlar yerleştirmek için entegre 2D kimyasal editörü kullanın veya katalogdan bilinen bir ilaç seçin.",
    step_02_title: "Hedef seçin",
    step_02_desc: "Moleküler kenetlenme (docking) simülasyonu yapmak istediğiniz protein veya biyolojik reseptörü seçin.",
    step_03_title: "Değerlendirin ve analiz edin",
    step_03_desc: "Bilgisayarınızın yapıyı 10 düzeyde nasıl değerlendirdiğini ve size blok zinciri sertifikası verdiğini görün.",
    stats_molecules: "Değerlendirilen Moleküller",
    stats_best_score: "En İyi Skor (kcal/mol)",
    stats_certified: "Blok Zinciri Sertifikaları",

    opt_appearance: "Görünüm",
    opt_theme: "Tema",
    opt_theme_dark: "Karanlık",
    opt_theme_light: "Aydınlık",
    opt_interface: "Arayüz Modu",
    opt_sounds: "Arayüz Sesleri",
    opt_sounds_muted: "Sesler sessizde",
    opt_sounds_active: "Sesler aktif",
    opt_sounds_activate: "Etkinleştirmek için tıkla",
    opt_sounds_silence: "Susturmak için tıkla",
    opt_ai: "AI Tercümanı",
    opt_ai_config: "AI sağlayıcısını yapılandır",
    opt_ai_chat_open: "MolChat'i Aç",
    opt_ai_chat_close: "MolChat'i Kapat",
    opt_data: "Veri & Yedekleme",
    opt_data_export: "Kütüphaneyi Dışa Aktar (JSON)",
    opt_data_export_desc: "Tüm moleküllerinizi ve sonuçlarınızı taşınabilir bir dosyada indirin",
    opt_data_export_success: "Yedek başarıyla dışa aktarıldı",
    opt_data_reset: "Oturum verilerini sıfırla",
    opt_data_reset_desc: "Aktif yerel oturumu kapatır. Değerlendirme geçmişi veritabanında saklanır.",
    opt_data_reset_warning: "Bu işlem çıkış yapmanızı sağlayacaktır. Molekülleriniz silinmeyecektir.",
    opt_data_reset_success: "Oturum sıfırlandı",
    opt_legal: "Yasal & Bilgi",
    opt_legal_terms: "Şartlar & Gizlilik",
    opt_legal_about: "Hakkında",

    legal_title: "Yasal Çerçeve — MolDesign AI",
    legal_tab_terms: "Kullanım Şartları",
    legal_tab_priv: "Gizlilik Politikası",
    legal_tab_lic: "Lisans",
    legal_local_first: "Local-First · Telemetri Yok · 100% Çevrimdışı",
    legal_understood: "Anlaşıldı",

    login_title: "Yerel Giriş",
    login_subtitle: "MolDesign, cihazınızda 100% yerel olarak çalışır.",
    login_username: "Kullanıcı Adı",
    login_password: "Şifre (En az 4 karakter)",
    login_btn: "Laboratuvara Gir",
    login_privacy_badge: "Verileriniz asla bu cihazdan dışarı çıkmaz.",
    login_error_fields: "Lütfen tüm alanları doğru şekilde doldurun.",
    login_error_auth: "Geçersiz kimlik bilgileri.",

    eval_title: "Moleküler Değerlendirme Paneli",
    eval_draw_tab: "1. Molekül Çiz",
    eval_target_tab: "2. Hedef Seç",
    eval_run_tab: "3. Simülasyon & Skor",
    eval_results_tab: "4. Son Rapor",
    eval_target_select_title: "Kenetlenme Hedefi Seçin",
    eval_target_desc: "Hangi protein reseptörüne karşı moleküler kenetlenme (Docking) simüle edileceğini seçin.",
    eval_run_simulation: "Bilimsel Simülasyonu Başlat",
    eval_docking_progress: "Moleküler kenetlenme simüle ediliyor...",
    eval_docking_success: "Moleküler kenetlenme başarıyla tamamlandı.",
    eval_docking_fail: "Kenetlenme simülasyonu sırasında hata oluştu.",
    eval_vina_score: "Vina Eğilimi",
    eval_admet_score: "ADMET Özellikleri",
    eval_solana_status: "Deneysel Solana kaydı",
    eval_solana_btn: "Devnet kaydını dene",

    moldex_title: "Moleküler Hedef Kütüphanesi (Moldex)",
    moldex_search: "Hedef ara...",
    moldex_table_pdb: "PDB ID",
    moldex_table_name: "Reseptör Adı",
    moldex_table_type: "Tür",
    moldex_table_resolution: "Çözünürlük",
  },
};

interface LanguageContextProps {
  locale: Locale;
  setLocale: (l: Locale) => void;
  t: (key: string) => string;
  currentLanguage: Language;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const { isLoading: authLoading, user } = useAuth();
  const [locale, setLocaleState] = useState<Locale>("es");
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    if (authLoading) return;
    try {
      const saved = getUserItem("moldesign_locale", user?.user_id) as Locale | null;
      if (saved && MVP_LOCALES.has(saved) && TRANSLATIONS[saved]) {
        setLocaleState(saved);
      } else {
        const navLang = navigator.language.split("-")[0] as Locale;
        if (MVP_LOCALES.has(navLang) && TRANSLATIONS[navLang]) {
          setLocaleState(navLang);
        }
      }
    } catch {}
    setHydrated(true);
  }, [authLoading, user?.user_id]);

  const setLocale = (l: Locale) => {
    if (!MVP_LOCALES.has(l) || !TRANSLATIONS[l]) return;
    setLocaleState(l);
    try {
      if (user) setUserItem("moldesign_locale", l, user.user_id);
    } catch {}
  };

  const t = (key: string): string => {
    const dict = TRANSLATIONS[locale] || TRANSLATIONS.es;
    return dict[key] || TRANSLATIONS.es[key] || key;
  };

  const currentLanguage = LANGUAGES.find((lang) => lang.code === locale) || LANGUAGES[0];

  if (!hydrated) {
    return (
      <LanguageContext.Provider value={{ locale: "es", setLocale: () => {}, t: (k) => TRANSLATIONS.es[k] || k, currentLanguage: LANGUAGES[0] }}>
        {children}
      </LanguageContext.Provider>
    );
  }

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

/**
 * Traducciones, sin tumbar el subárbol cuando falta el provider.
 *
 * ANTES LANZABA. Un componente que sólo quería dos etiquetas derribaba todo lo
 * que colgara de él si alguien lo montaba fuera del provider — que es
 * exactamente la clase de fallo que deja la ventana en blanco. Un texto que no
 * se puede traducir es un problema de idioma, no de disponibilidad: se degrada
 * al castellano, que es el idioma base del diccionario, y se avisa una vez en
 * consola para que el montaje mal hecho no pase inadvertido.
 */
export function useLanguage(): LanguageContextProps {
  const ctx = useContext(LanguageContext);
  if (ctx) return ctx;

  if (typeof console !== "undefined" && !avisoDeProviderEmitido) {
    avisoDeProviderEmitido = true;
    console.warn(
      "[LanguageContext] useLanguage fuera de LanguageProvider: se usa el " +
        "diccionario en castellano. Revisa dónde se monta este componente.",
    );
  }
  return RESPALDO_SIN_PROVIDER;
}

let avisoDeProviderEmitido = false;

const RESPALDO_SIN_PROVIDER: LanguageContextProps = {
  locale: "es",
  setLocale: () => {},
  t: (key: string) => TRANSLATIONS.es[key] ?? key,
  currentLanguage: LANGUAGES[0],
};
