import type { ModuloDeTraduccion } from "./index";

export const cierre: ModuloDeTraduccion = {
  es: {
    z_molchat_interprete: "MolChat - Intérprete IA",
    z_targets_comunidad: "Targets de la Comunidad",
    z_pains_explicacion: "Los PAINS son falsos positivos frecuentes en ensayos biológicos (Baell & Holloway, 2010). Se recomienda validación experimental exhaustiva antes de considerar esta molécula como hit.",
    z_cargando_pro: "Cargando evaluación pro...",
    z_red_viabilidad: "Red de Viabilidad (Lipinski)",
    z_limite_ideal: "Límite Ideal",
    z_identificar_diseno: "Identificar Mi Diseño",
    z_panel_selectividad: "Panel de Selectividad",
    z_dockea_antitargets: "Dockea contra el panel declarado de anti-targets",
    z_propiedades_fq: "Propiedades Físico-Químicas",
    z_contexto_scoring: "Contexto de Scoring",
    z_perfil_sanguineo: "Perfil Sanguíneo (índice)",
    z_analisis_sar: "Análisis SAR — Estructura-Actividad",
    z_consultando_analogos: "Consultando análogos estructurales...",
    z_sin_analogos: "Sin análogos disponibles aún — evaluá más moléculas contra el mismo receptor para poblar el SAR.",
    z_config_parametros: "Configuración de Parámetros",
    z_catalogo_receptores: "Catálogo de Receptores",
    z_familia_quimica: "Familia Química",
    z_familia_terapeutica: "Familia Terapéutica",
    z_comunidad_cientifica: "Comunidad Científica",
    z_buscar_receptor: "Buscar por PDB ID, nombre de la proteína, o familia...",
    z_sin_vista_previa: "Sin Vista Previa",
    z_comparador_no_cargo: "No se pudieron cargar la pose y el receptor de esta molécula. El archivo puede no estar disponible o no estar autorizado para tu cuenta.",
    z_comparador_titulo: "COMPARADOR DE LIGANDOS",
    z_no_comparables: "Estas moléculas no son comparables",
    z_no_comparables_detalle: "Las propiedades fisicoquímicas de cada molécula se muestran arriba y siguen siendo válidas por separado. Lo que no puede calcularse es la diferencia entre ellas.",
    z_benzaldehido: "C₇H₆O · Benzaldehído · Pipeline Tecnológico",
    z_3d_no_dibuja: "La vista 3D no se puede dibujar en este equipo",
    z_3d_datos: "Los datos de esta pose y sus descargas no dependen del visor: siguen disponibles, y el archivo descargado se abre en cualquier visor externo.",
    z_3d_al_terminar: "La vista 3D aparece cuando termina el acoplamiento",
    z_hit: "Contacto (&lt; 3.5Å)",
    z_proximity: "Proximidad (&lt; 5.0Å)",
    z_miss: "Sin contacto (&gt; 5.0Å)",
    z_camera_locked: "Cámara bloqueada durante el desplazamiento",
    z_unlock_3d: "Desbloquear vista 3D",
    z_lock_3d: "Bloquear vista 3D",
    z_critical_hit: "Contacto crítico",
    z_critical_hit_desc: "Puente de hidrógeno o enlace iónico fuerte por debajo de 3.5 Å.",
    z_proximity_contact: "Contacto próximo",
    z_proximity_contact_desc: "Proximidad inferior a 5.0 Å. Contribuye mediante fuerzas de van der Waals.",
    z_miss_desc: "Lejos del hotspot (> 5.0 Å). Interacción escasa o nula.",
    z_datos_eliminados: "✓ Datos locales eliminados. Por favor reinicia la aplicación.",
    z_ruta_reportes: "Ruta de Descarga PDF / Reports",
    z_acelerador: "Acelerador de Partículas",
    z_simulacion_visual: "Simulación Visual",
    z_alertas_sa: "Alertas de Accesibilidad (SA)",
    z_absorcion_intestinal: "Absorción Intestinal",
    z_spearman_pendiente: "(Spearman: Pendiente de recálculo)",
    z_advertencias_cientificas: "⚠ Advertencias Científicas",
    z_notas_integridad: "Notas de Integridad de Datos",
    z_girar_3d: "Arrástrame para girar · Click derecho para mover · Doble click para detalles",
    z_cerrar_ayuda: "Cerrar la ayuda",
    z_temperatura: "0 = Analítico (Química), 1 = Creativo",
    z_registro_telemetria: "Registro de Telemetría",
    z_esperando_pipeline: "Esperando datos del pipeline...",
    z_bioteca_vacia: "Bioteca vacía.",
    z_algo_salio_mal: "Algo salió mal",
    z_descarga_de: "Descarga de {name}",
    z_ver_controles_pose: "Ver controles físicos de la pose #{rank}",
    z_ver_informe: "Ver informe",
    z_descargar_pdf: "Descargar PDF",
    z_guardado_moldex: "Guardado en Moldex",
    z_guardar_moldex: "Guardar en Moldex",
    z_verificado_solana: "Verificado en Solana",
    z_registrar_blockchain: "Registrar en blockchain",
    z_descargar_complejo_pdb: "Descargar complejo PDB",
    z_creado_tabpfn: "Creado con PriorLabs-TabPFN",
    z_admet_note: "Módulo experimental. Se ejecuta EN LOCAL, en esta máquina: la primera carga del modelo puede tardar varios minutos —especialmente en una máquina virtual o sin GPU— y bloquea el avance de la corrida mientras ocurre. NO es necesario para el docking: apagado, el acoplamiento y sus puntuaciones se calculan igual, y el panel de Parámetros queda sin predicción farmacocinética en vez de mostrar una inventada.",
    z_no_severity: "Sin severidad declarada",
    z_document_title: "MolDesign — Evidencia estructural reproducible",
  },
  en: {
    z_molchat_interprete: "MolChat - AI interpreter",
    z_targets_comunidad: "Community targets",
    z_pains_explicacion: "PAINS are frequent false positives in biological assays (Baell & Holloway, 2010). Thorough experimental validation is recommended before considering this molecule a hit.",
    z_cargando_pro: "Loading pro evaluation...",
    z_red_viabilidad: "Viability web (Lipinski)",
    z_limite_ideal: "Ideal limit",
    z_identificar_diseno: "Identify my design",
    z_panel_selectividad: "Selectivity panel",
    z_dockea_antitargets: "Dock against the declared anti-target panel",
    z_propiedades_fq: "Physicochemical properties",
    z_contexto_scoring: "Scoring context",
    z_perfil_sanguineo: "Blood profile (index)",
    z_analisis_sar: "SAR analysis — structure–activity",
    z_consultando_analogos: "Looking up structural analogues...",
    z_sin_analogos: "No analogues are available yet — evaluate more molecules against the same receptor to populate the SAR analysis.",
    z_config_parametros: "Parameter settings",
    z_catalogo_receptores: "Receptor catalogue",
    z_familia_quimica: "Chemical family",
    z_familia_terapeutica: "Therapeutic family",
    z_comunidad_cientifica: "Scientific community",
    z_buscar_receptor: "Search by PDB ID, protein name or family...",
    z_sin_vista_previa: "No preview",
    z_comparador_no_cargo: "The pose and receptor for this molecule could not be loaded. The file may be unavailable or not authorised for your account.",
    z_comparador_titulo: "LIGAND COMPARATOR",
    z_no_comparables: "These molecules are not comparable",
    z_no_comparables_detalle: "Each molecule's physicochemical properties are shown above and remain valid separately. The difference between them cannot be calculated.",
    z_benzaldehido: "C₇H₆O · Benzaldehyde · Technology pipeline",
    z_3d_no_dibuja: "The 3D view cannot be rendered on this device",
    z_3d_datos: "The data for this pose and its downloads do not depend on the viewer: they remain available, and the downloaded file opens in any external viewer.",
    z_3d_al_terminar: "The 3D view appears when docking finishes",
    z_hit: "Hit (&lt; 3.5Å)",
    z_proximity: "Proximity (&lt; 5.0Å)",
    z_miss: "Miss (&gt; 5.0Å)",
    z_camera_locked: "Camera locked while scrolling",
    z_unlock_3d: "Unlock 3D view",
    z_lock_3d: "Lock 3D view",
    z_critical_hit: "Critical hit",
    z_critical_hit_desc: "Strong hydrogen bond or ionic interaction below 3.5 Å.",
    z_proximity_contact: "Proximity contact",
    z_proximity_contact_desc: "Proximity below 5.0 Å. Contributes through van der Waals forces.",
    z_miss_desc: "Far from the hotspot (> 5.0 Å). Little or no interaction.",
    z_datos_eliminados: "✓ Local data deleted. Please restart the application.",
    z_ruta_reportes: "PDF/report download path",
    z_acelerador: "Particle accelerator",
    z_simulacion_visual: "Visual simulation",
    z_alertas_sa: "Synthetic accessibility alerts (SA)",
    z_absorcion_intestinal: "Intestinal absorption",
    z_spearman_pendiente: "(Spearman: recalculation pending)",
    z_advertencias_cientificas: "⚠ Scientific warnings",
    z_notas_integridad: "Data integrity notes",
    z_girar_3d: "Drag to rotate · Right-click to pan · Double-click for details",
    z_cerrar_ayuda: "Close help",
    z_temperatura: "0 = Analytical (chemistry), 1 = Creative",
    z_registro_telemetria: "Telemetry log",
    z_esperando_pipeline: "Waiting for pipeline data...",
    z_bioteca_vacia: "The library is empty.",
    z_algo_salio_mal: "Something went wrong",
    z_descarga_de: "Download of {name}",
    z_ver_controles_pose: "View physical checks for pose #{rank}",
    z_ver_informe: "View report",
    z_descargar_pdf: "Download PDF",
    z_guardado_moldex: "Saved in Moldex",
    z_guardar_moldex: "Save in Moldex",
    z_verificado_solana: "Verified on Solana",
    z_registrar_blockchain: "Register on blockchain",
    z_descargar_complejo_pdb: "Download PDB complex",
    z_creado_tabpfn: "Built with PriorLabs-TabPFN",
    z_admet_note: "Experimental module. It runs LOCALLY on this machine: the first model load can take several minutes—especially in a virtual machine or without a GPU—and blocks run progress while it loads. It is NOT required for docking: when disabled, docking and its scores are calculated normally, and the Parameters panel remains without a pharmacokinetic prediction instead of showing an invented one.",
    z_no_severity: "No declared severity",
    z_document_title: "MolDesign — Reproducible structural evidence",
  },
};
