import type { ModuloDeTraduccion } from "./index";

export const generadas: ModuloDeTraduccion = {
  es: {
    auto_5bcd0dc46b99: "— fuera del dominio de aplicabilidad; se muestra como referencia, no como predicción.",
    auto_c8b9d71daaca: "— informativa, con peso 0 en el ranking",
    auto_e3213d2976ba: "— la corrida no registró si cayó dentro del dominio de aplicabilidad.",
    auto_988351833ce1: "— Ranqueados por score",
    auto_99b5f43f6422: ", así que no hay informe que abrir. El identificador sigue guardado:",
    auto_8ff2cb920103: ", ninguno con resultado guardado todavía",
    auto_5bab61eb5317: "?",
    auto_cc3fb7ae5b1e: ". La carpeta que has elegido es",
    auto_dc0b31771c0b: ". La estructura plegada se conserva como evidencia, sin afinidad.",
    auto_a0c51a5fc4c9: ". Los números de cada ficha se leen del manifest en cada build: la prosa no puede desviarse de ellos sin que se note. Un experimento sellado después de esa fecha todavía no está aquí.",
    auto_3cbb86a7ea90: ". No se movió nada; puedes reintentarlo.",
    auto_ea64cf436cb0: ". Puedes llevarlo a tu cuenta ahora. Se mueve, no se copia: dejará de estar en la cuenta invitada.",
    auto_a6cdeb7c5844: ". Sin API key.",
    auto_d970f808cba3: ". Sólo existe en memoria:",
    auto_655a8de817b6: "· señales heredadas disponibles solo como traza técnica",
    auto_73e38ad50e54: "· sin autorizar",
    auto_d524488efd51: "· uso comercial con licencia separada",
    auto_7a133b421d46: "(function(){ try { var auth = JSON.parse(localStorage.getItem(\"moldesign_auth\") || \"null\"); var userId = auth && auth.user && auth.user.user_id; var saved = userId ? localStorage.getItem(\"moldesign_theme:user:\" + userId) : null; if (saved === \"light\") { document.documentElement.classList.remove(\"dark\"); document.documentElement.classList.add(\"light\"); } } catch(e) {} })();",
    auto_4d382c8b0332: "(function(){ var s = document.createElement('script'); s.src = '/3Dmol-min.js'; s.onerror = function(){ console.warn('[MolDesign] 3Dmol-min.js no encontrado en /public/. Visualizador 3D no disponible. Reinstala la app o ejecuta npm run dev.'); }; document.head.appendChild(s); })();",
    auto_0ce6ec21b144: ") no usada — llama-cpp-python sin CUDA",
    auto_1765f4131521: ") y crea un receptor privado nuevo. El original no cambia.",
    auto_d45dcd15ff99: "). El resultado lo sostienen las señales que sí opinaron, con los pesos renormalizados que aparecen en cada tarjeta. La descripción de la familia y su nota de abajo siguen describiendo el diseño, no lo que pasó aquí.",
    auto_5c7c8c2f3b8e: "). El veredicto de arriba se calculó sin ellas, así que puede ser optimista.",
    auto_1358197dcf7b: "× el tiempo de acoplamiento. Amplía la cobertura geométrica; no mejora, por sí solo, la elección de la pose top-1.",
    auto_6dbd2d03ab5b: "▲ Contribución positiva en este modelo",
    auto_2d325f1fbc1d: "▼ Contribución negativa en este modelo",
    auto_c4bcead81aba: "✓ Señal positiva",
    auto_3963e4218261: "✗ Señal negativa",
    auto_7167a3bad96d: "a favor de la diana principal, por la dispersión de ±",
    auto_1f88e3bba8e6: "Abrir sin módulos opcionales",
    auto_4d2183484683: "Abrir una muestra el resultado que produjo esa corrida; no reemplaza la evaluación que tienes en pantalla ni vuelve a ejecutar nada.",
    auto_ad4e898dd924: "Absorción intestinal, permeabilidad BBB, PPB, solubilidad LogS y alertas de reactividad, con ADMET-AI (Chemprop D-MPNN). El consenso de BBB acierta 39 de 41 fármacos de difusión pasiva en una cohorte de regresión de 46, sin holdout independiente: es la cifra con la que se ajustó, no una validación externa. El índice de perfil sanguíneo es heurístico.",
    auto_0d82ae16ddd4: "Aceptores de Puentes de Hidrógeno (HBA)",
    auto_b12bc4e545ec: "Acoplamiento contra los 5 anti-targets del panel (ANTI_TARGET_PANEL): hERG/KCNH2 5VA1 (cardiotoxicidad), CYP3A4 4NY4 (interacciones), 5-HT2B 4NC3 (valvulopatía), PDE3A 1SO2, NaV1.5/SCN5A 6MVW (conducción cardíaca). Da el margen on/off-target; no emite un veredicto de seguridad.",
    auto_29368dd6d018: "ADME reúne señales computacionales de absorción, distribución, metabolismo y excreción. Este índice sirve para comparar moléculas dentro del protocolo; no predice por sí solo cómo responderá una persona.",
    auto_2ab36069225c: "ADMET-AI no se ejecutó en esta corrida",
    auto_6cb48f8ad846: "advertencia(s) de generación; consulta el dossier para el detalle.",
    auto_73dfe1bf7b4c: "Afinidad (score de docking)",
    auto_5542e5a19746: "ALERTA DE UMBRAL",
    auto_6b882e73c6d3: "Alerta(s) de Off-Target Rebasados",
    auto_0ec637ca2747: "AlphaFold-Multimer para complejos proteína-péptido.",
    auto_f3837875dab4: "Alto — cumple la mayoría de estas reglas heurísticas",
    auto_5fd84e29ad40: "Amida más larga; donor y acceptor de H-bonds.",
    auto_062164e36e14: "Amida; donor y acceptor de H-bonds.",
    auto_20974a2a67a6: "Amino (+); sal bridge con ligandos ácidos, cation-π.",
    auto_54ecc2e4a2ee: "Anillo aromático; interacciones π-stacking con ligandos aromáticos.",
    auto_98d8f5a99754: "Área de Superficie Polar Topológica (TPSA)",
    auto_11bdeb08e4bf: "Artefacto de investigación para representar contactos proteína–ligando. No se presenta como verificador físico ni como motor disponible si sus dependencias o pesos no están presentes en esta instalación.",
    auto_0fbfc17c9782: "Artefacto de rescoring experimental que representa contactos de una pose. No emite automáticamente Kd/Ki en esta instalación ni valida por sí solo la geometría.",
    auto_7520b27b9116: "Artefacto experimental que representa contactos proteína–ligando. No valida por sí solo la geometría ni emite Kd/Ki en esta instalación.",
    auto_d0b584a74983: "asigna peso por diseño",
    auto_b6be6414756b: "Asistente opcional con Qwen2.5-1.5B local que consulta evidencia persistida y ayuda a explicarla. No es fuente primaria de resultados; requiere el modelo instalado y no incluye voz local en este runtime.",
    auto_7f2537d04d9e: "átomo(s) con coordenadas de ESMFold y",
    auto_808cfa7d641c: "Átomos de proteína",
    auto_ba93a478fc9b: "AUMENTA la afinidad predicha",
    auto_2f68d2558c76: "AutoDock Vina 1.2.7 explora poses dentro de la caja declarada y devuelve un score empírico para ordenar poses. No es energía libre experimental.",
    auto_84d405785c17: "Azufre en la cadena lateral; puede hacer contactos S-π o S-H.",
    auto_32e8785f56fe: "Bajo — varias reglas heurísticas no se cumplen",
    auto_324dd8981c4f: "Balanceado — buen rendimiento sin ralentizar el equipo",
    auto_1856b6561e91: "Cada dimensión de la caja debe estar entre 5 y 80 Å.",
    auto_f4940abeb43f: "Cadena lateral ramificada; contactos de van der Waals con ligandos lipofílicos.",
    auto_68483034f561: "Calcula descriptores y reglas de drug-likeness para contextualizar la estructura. No garantiza absorción, seguridad ni viabilidad oral.",
    auto_1da2cfab4f02: "Calculando con OpenMM... (",
    auto_aa7e38e37678: "Cancelado por el usuario",
    auto_04230d165336: "Carboxilato (−); iónico/sal bridge, acceptor fuerte de H-bond.",
    auto_9559239a0af7: "Carboxilato (−); sal bridge, reconocimiento de cationes.",
    auto_443a6fd91b4e: "carga del modelo puede tardar varios minutos —especialmente en una",
    auto_56307dd72ba4: "Cargas iónicas y puentes de hidrógeno cargados",
    auto_1daed134ce8c: "Centro de la caja (Å)",
    auto_36049ba7faf6: "Cercanía entre nitrógenos donadores del ligando y carbonos del bolsillo. NO es un puente de hidrógeno: el carbono no tiene pares libres ni la electronegatividad para aceptarlo. Mide empaquetamiento y polarización.",
    auto_09f5a9e4d304: "Cercanía entre oxígenos donadores del ligando y carbonos del bolsillo. NO es un puente de hidrógeno, por la misma razón: el carbono no acepta. Mide empaquetamiento.",
    auto_416ef02a1420: "Cobertura de entrada:",
    auto_f2422134496a: "Coeficiente de Partición (LogP)",
    auto_9835328903b8: "Comparación de propiedades entre",
    auto_aa8a3c091711: "Completa el nombre, la cadena y las seis coordenadas.",
    auto_c0a10228aed3: "completado(s) con",
    auto_7417a14c6944: "Comprueba geometría, choques, conectividad e interacciones bajo los controles disponibles. RMSD sólo es interpretable cuando existe una referencia compatible.",
    auto_b1f6e510eb0f: "con",
    auto_f24ed0ca4042: "con resultado",
    auto_121e3999ff64: "con tu cuenta local",
    auto_0229a5139372: "Conectate para ver targets compartidos",
    auto_fb21ded85274: "Conservador — no sobrecarga la CPU",
    auto_146267f4301a: "Contacto hidrofóbico frecuente en bolsillos de unión.",
    auto_932e50554e31: "Contactos atómicos con grupos fosfato.",
    auto_dc3304d88376: "Contactos atómicos entre Carbonos y Nitrógenos.",
    auto_608b11c2a2f3: "Contactos atómicos entre Carbonos y Oxígenos.",
    auto_83a92d919084: "Contactos de largo alcance en el borde del solvente o la superficie proteica exterior.",
    auto_5bcb436809b0: "Contactos de medio alcance entre Carbonos y Oxígenos.",
    auto_4b4916d3dc86: "Contactos hidrofóbicos entre átomos de Carbono del ligando y de la proteína.",
    auto_c359f0cd7a14: "Conteo de conformaciones no registrado",
    auto_01a2c44be46f: "contra este mismo receptor.",
    auto_d8233986780e: "Controles físicos de pose",
    auto_f1037aec2a80: "Copiar dirección de Solana",
    auto_262949a66911: "Corrida pendiente de registro",
    auto_0ef026dc501a: "Costo de desolvatación polar (Generalized Born)",
    auto_ce0ad0ebf48a: "Crea otro caso para evaluar un sistema estructural distinto.",
    auto_8cd782f9aaaa: "Criterio de aceptación declarado antes, y cumplido.",
    auto_9eca858843aa: "Cruza sólo las señales que el perfil declara y que la corrida produjo. Conserva observación, score derivado, aplicabilidad y abstención; no equivale a un consenso universal ni a una conclusión experimental.",
    auto_9d0f79ed0388: "cuenta, pero la corrida sigue identificada: recupera la sesión y usa «Reintentar seguimiento».",
    auto_600ccd1b7156: "de",
    auto_c1b398a5da7e: "de sellar invalidó las cifras de este registro.",
    auto_c5324603beef: "Densidad atómica en la cavidad de unión extendida.",
    auto_b099e128531e: "Densidad atómica en un anillo tridimensional específico.",
    auto_481656be8588: "Densidad de Carbonos alrededor del ligando en la franja de distancia media de 4 a 8 Ångströms.",
    auto_2e8b40078ffb: "Densidad de Nitrógenos interactuando fuertemente a menos de 4 Ångströms.",
    auto_d5586e61a936: "Densidad de Oxígenos en un rango intermedio alrededor del ligando.",
    auto_5b09d65f54ac: "Densidad de pares Carbono-Nitrógeno en contacto íntimo (< 4 Å). Puede reflejar puentes de H implícitos o empaquetamiento polar cercano.",
    auto_bea13b26dbec: "Densidad de pares Oxígeno-Carbono en el borde del solvente (8-10 Å). Contribuye al contexto estérico de largo alcance.",
    auto_9a3561c18fde: "dentro de Lipinski",
    auto_4696a2a82a01: "dentro de Veber",
    auto_0e4b9698dddb: "dentro del umbral",
    auto_b35a21592ba5: "Descriptor 1D/2D del ligando. Las moléculas más pesadas pueden correlacionar con cambios sistemáticos en el score del modelo.",
    auto_54dd883d2597: "Descriptores de GFN2-xTB (cargas tight-binding, gap HOMO-LUMO, energía) y de MMFF94, ~0.1 s/mol. El índice agregado que produce es una combinación lineal con pesos elegidos a mano: informa y se guarda, pero desde 2026-09-04 no entra al score principal. No es equivalente a GAFF2 ni a un cálculo DFT.",
    auto_a8e7405da2c4: "desde la corrida",
    auto_a2f32be1b030: "Desglose de Farmacóforos",
    auto_318b7c221101: "Detecta grupos funcionales candidatos a coordinar zinc desde la estructura química, sin ejecutar docking. Es una señal de protocolo para perfiles M5-Zn concretos; no es un cálculo cuántico ni una conclusión general de actividad.",
    auto_6b74eaabc080: "Detector SMARTS de grupos funcionales candidatos a coordinar metales. Sólo se integra mediante perfiles M5-Zn exactos; su estado, componentes y aplicabilidad se muestran sin fabricar una fórmula fuera de perfil.",
    auto_e53d65c119b2: "Dictado no disponible: esta instalación no incluye reconocimiento de voz local",
    auto_1416d9865ffd: "Dictar por voz con el modelo local",
    auto_d2b216252962: "Diferencia entre la mejor y la peor pose de docking. Indica qué tan discriminante es el score en el espacio conformacional muestreado.",
    auto_9331807fc431: "Difusión SE(3)-equivariante (Baker Lab). GPU requerida.",
    auto_408d39d8cace: "Diseño de la familia:",
    auto_c56fdd911c69: "Dispersión de las afinidades entre las poses generadas. Una varianza alta sugiere un bolsillo ambiguo con múltiples modos de unión.",
    auto_15390043b6c6: "Docking local dentro de la caja declarada. Explora poses y devuelve un score empírico de Vina; no afirma una pose termodinámicamente óptima ni una energía libre experimental.",
    auto_411c9577cc23: "Donadores de Puentes de Hidrógeno (HBD)",
    auto_d59e25441a19: "Efectos conformacionales y estéricos de largo alcance ejercidos por los Carbonos del bolsillo.",
    auto_91d8ff3aff6a: "El archivo de poses no contiene las dos poses seleccionadas. La corrida se conserva sin sustituir sus datos.",
    auto_9efee153557b: "El caso fue liberado; puedes reintentar el seguimiento más tarde.",
    auto_4bf26aa090e9: "El contexto molecular disponible se adjunta a cada turno.",
    auto_5e8ef3521b05: "El dossier no se pudo generar.",
    auto_b3945ccefff7: "El informe está disponible, pero este caso no conserva una huella verificable de los inputs ejecutados.",
    auto_b0407faa7b48: "El motor está preparándose. La evaluación estará disponible en cuanto responda.",
    auto_74f10d125232: "El motor local está terminando de arrancar. Reintentando automáticamente…",
    auto_4b66d3c2fe33: "El nombre de usuario es obligatorio.",
    auto_1171a79e25ba: "El perfil está calculado y guardado con la corrida: aparece en",
    auto_f0d9b3df714d: "El pH usado queda escrito en el expediente.",
    auto_225f4287b89f: "El pipeline está corriendo el panel en background; el resultado aparecerá solo.",
    auto_8819735dd62d: "El receptor está fijado por la primera corrida de este caso.",
    auto_dae68ac9b41e: "El resultado puede seguir existiendo: esto dice que ahora mismo no se ha podido leer, no que se haya perdido.",
    auto_8a59609e15c0: "el score como evidencia de afinidad.",
    auto_3a94369c8527: "El score de Vina es una función empírica de puntuación, no una energía libre medida, y su dispersión frente a afinidades experimentales es de unos ±",
    auto_383ad4c4bf5b: "El score de Vina ordena poses bajo el protocolo declarado. Sirve como señal empírica de afinidad relativa; no es una medición experimental de energía libre ni de actividad.",
    auto_f772d2e3af48: "El visor 3D no está disponible en este equipo.",
    auto_4356059ccdf0: "El visor científico (Mol*) no pudo iniciarse en este equipo.",
    auto_32983b1d7ac2: "Email y contraseña son obligatorios.",
    auto_703e06c21c31: "En condiciones ideales a 298 K, una diferencia de 8 kcal/mol implica una relación termodinámica aproximada de 10^5–10^6; Vina no mide directamente esa energía libre.",
    auto_1efcd5b46d53: "en este equipo, aunque «",
    auto_324033e95c09: "En modo manual debes proveer las coordenadas (X, Y, Z) del centro del sitio activo.",
    auto_f459de5d43b3: "En una máquina virtual, habilitar la GPU virtualizada del hipervisor puede resolverlo.",
    auto_0a42461c773d: "Error al cargar coordenadas en el visualizador.",
    auto_15eff5b3b975: "Error al cargar el reporte",
    auto_090a83af1bac: "Error sin mensaje.",
    auto_09cd68a2a77b: "es",
    auto_c4bbdea3891b: "Es",
    auto_9debabbaa01a: "ES",
    auto_6982bfeae501: "Es porque",
    auto_91249e5adbba: "es-ES",
    auto_e5274e78712c: "es-MX",
    auto_a187157bca8f: "Escalabilidad del Pipeline",
    auto_14578be07d4d: "ESMFold operativo para plegamiento; la conversión a ligando acoplable aún no soportada, así que el acoplamiento no se evalúa.",
    auto_4cce270ad33f: "Especificidad de Diana",
    auto_946f5d999b58: "Específico de familia",
    auto_9a8c2888bccd: "Esta corrida no tiene predicción farmacocinética: ADMET-AI no llegó a ejecutarse, sea porque estaba desactivado en las opciones de la corrida o porque el modelo no se pudo cargar en este equipo. Los campos de abajo están vacíos porque no se midió nada,",
    auto_28590748cd34: "Esta cuenta todavía no autorizó ese destino.",
    auto_bf1431bba866: "Esta función requiere",
    auto_57652532d30f: "Esta molécula pertenece a otra cuenta. Inicia sesión con la cuenta con la que la evaluaste para guardarla en tu MolDex.",
    auto_265b259a1293: "Este caso guarda una corrida completada, pero",
    auto_248db3e9f594: "Este equipo expone 3D, pero no con lo que Mol* necesita para dibujar.",
    auto_49e5b55bba06: "Este panel se ejecutó pero no se pudo escribir en la evaluación: si cambias de pestaña lo pierdes, y el informe dirá que no se registró ningún anti-target.",
    auto_dbfb7d741250: "este receptor. Trata el resultado como una hipótesis: no cites",
    auto_e68b364d222e: "Estima un ΔG MM-GBSA sobre la pose seleccionada",
    auto_dc39d5d9367f: "Estimación post-hoc de ΔG con MM-GBSA y solvente implícito (OpenMM OBC2)",
    auto_bf0382f209fa: "Evalúa contra 5 receptores de seguridad (hERG, CYP3A4, 5-HT2B, PDE3A, NaV1.5)",
    auto_15eb472d4323: "Evalúa si tu molécula cumple las reglas históricas para ser una buena pastilla oral.",
    auto_0d93be49ed45: "Evidencia de auditoría",
    auto_7786e423c133: "Excelente balance entre velocidad y razonamiento científico local.",
    auto_7c3ae9bd54e6: "Falta el valor en al menos una de las dos moléculas",
    auto_fdcf2203371a: "Fenol; π-stacking + H-bond donor/acceptor por el OH.",
    auto_a2b452f155f4: "Ficha del registro sellado",
    auto_b05b976cbc9e: "fuera de Lipinski",
    auto_715e0e63b8f6: "fuera de Veber",
    auto_2ccc163e69dd: "fuera del umbral",
    auto_ce040e015442: "GB). Se usará al cargar.",
    auto_8ccbd006d5fd: "Genera conformaciones 3D plausibles mediante restricciones geométricas y muestreo estocástico. No demuestra que una conformación sea la dominante en solución.",
    auto_e1592998873b: "Genera los datos con",
    auto_0c7048843eda: "Genera un PDF con la evidencia y sus identificadores verificables. Puede incluir un enlace de integridad a Solana cuando el usuario lo solicita; no transfiere la propiedad de la molécula, el caso ni sus resultados.",
    auto_65299f4a07a8: "Gestionar módulos de simulación",
    auto_24300640c524: "GFN2-xTB, tight-binding semi-empírico — no DFT. Calcula HOMO/LUMO, momento dipolar, cargas parciales y polarizabilidad en ~0.1 s/mol. No es equivalente a GAFF2: son campos de fuerza distintos y aquí no se ha medido ninguna correspondencia. El índice agregado que produce es heurístico y desde 2026-09-04 no entra al score principal.",
    auto_887c159b9e2f: "Grafo del SMILES conservado;",
    auto_4c9d11deb414: "Grafo local en SQLite y FTS5 que organiza moléculas, targets, evaluaciones y evidencia para que MolChat consulte hechos persistidos. Mejora el contexto recuperado, pero no garantiza cero alucinaciones ni sustituye la validación científica.",
    auto_f12bbb9518b1: "Guanidinio (+); sal bridge fuerte, reconocimiento de fosfatos.",
    auto_7f0c5ddda6e9: "Hay evidencia recuperable de una corrida ANTERIOR: los inputs han cambiado desde que se ejecutó.",
    auto_90ca0c04628c: "Herramienta disponible para operaciones de preparación y minimización configuradas explícitamente. MolDesign no ejecuta dinámica molecular de producción ni FEP con este componente.",
    auto_d9d584c1546b: "Herramienta disponible para operaciones explícitamente configuradas de preparación o minimización. MolDesign no ejecuta MD de producción ni FEP con ella.",
    auto_b8c87de15d58: "Herramienta local con código fuente público para preparar, evaluar y documentar evidencia estructural reproducible y auditable.",
    auto_f288a26eee67: "Heurística de accesibilidad sintética (1–10). Es una señal orientativa sobre complejidad molecular, no un precio ni una garantía de que la síntesis sea posible.",
    auto_2aac960c125c: "Hidrofóbico; define la forma del bolsillo.",
    auto_cb3645865abe: "Hipótesis propias puestas a prueba y derribadas. De aquí salió casi todo lo aprendido.",
    auto_6c6d4fcf3374: "Hubo un error en la descarga.",
    auto_fa14698a6e5a: "Ideas propias puestas a prueba y refutadas. De aquí salió casi todo lo aprendido.",
    auto_eeb11cc0b66e: "Idioma de dictado: español",
    auto_dda6b46d3faf: "Idioma de dictado: inglés",
    auto_c1b0533bca64: "Inicia sesión cloud para compartir con atribución.",
    auto_3c658efb0bdc: "Inicia sesión para guardar moléculas en tu MolDex. El guardado requiere una cuenta para asociar la molécula a tu perfil.",
    auto_f56a50a80039: "Inicia sesión para guardar moléculas en tu MolDex. Tu sesión expiró o no está activa.",
    auto_7194e52d2e3f: "Instala sólo lo que necesites. Cada archivo se verifica mediante SHA-256 antes de quedar disponible para MolDesign.",
    auto_df4742f77e88: "Integración opcional que registra un hash y metadatos técnicos en un memo público. Puede verificar integridad y fecha de emisión; no valida la ciencia ni publica automáticamente la estructura.",
    auto_8c64c2a0e530: "Interacción específica de pares atómicos (ECIF).",
    auto_898e5bcf715e: "Interacciones hidrofóbicas y de contacto estérico",
    auto_ed428b8dc80c: "Intermedio — cumple parte de estas reglas heurísticas",
    auto_fef3df333005: "Interpretación del perfil",
    auto_2033c07d6b2e: "Intervalo de",
    auto_e2dcdd634166: "kcal/mol — que en escala exponencial son más de dos órdenes de magnitud. El intervalo de arriba es lo máximo que este número sostiene. Úsalo para ordenar anti-dianas entre sí, no para decidir si una concentración es segura.",
    auto_8c4ac216c830: "kcal/mol del score de Vina.",
    auto_222f750aceb4: "La carpeta",
    auto_0af4040d3c39: "La contraseña debe tener al menos 8 caracteres.",
    auto_d03d4fc90d79: "La corrida arrancó pero su identificador no se pudo guardar en el caso.",
    auto_66c8de9b17f6: "La corrida no corresponde a los inputs actuales. Corrige la hipótesis o abstente.",
    auto_990cc7b4b8ec: "La corrida no devolvió un receptor o un archivo de poses utilizable para comparar.",
    auto_5dc69e1ba19b: "La corrida terminó y su evidencia se puede recuperar.",
    auto_471ce73812dc: "La disposición no se pudo guardar. Revisa la justificación.",
    auto_1e4b0441cf79: "La entrada no supera una comprobación estructural. Se conserva el motivo y se bloquea la etapa que no puede ejecutarse; no se elimina silenciosamente el caso.",
    auto_57d409b275d3: "La molécula se reevaluó después de certificarla: el sello atestigua una corrida anterior, no la que se muestra.",
    auto_d789b996261e: "La molécula se reevaluó después de registrar su recibo. La cadena conserva un índice histórico de",
    auto_aca79297777a: "La ruta del documento legal no pertenece a los assets locales.",
    auto_b5b351f33de7: "La tabla compara evaluaciones disponibles contra el mismo receptor. La similitud usa Tanimoto sobre el fingerprint topológico de RDKit; los deltas sólo aparecen cuando ambas corridas conservan la métrica correspondiente.",
    auto_567d82bb53d9: "La tarea ya no estaba activa. Actualizamos su estado con el backend.",
    auto_ebb21b20058c: "Las contraseñas no coinciden.",
    auto_35f6dace8ff1: "Las cuatro reglas de Lipinski son filtros históricos para comparar compuestos orales. Incumplir una regla no descarta una molécula ni equivale a toxicidad o fracaso clínico.",
    auto_db0393069f56: "las mide de nuevo y las sustituye. Este artefacto no se reescribe ni se re-sella: se conserva tal como quedó, para que la corrección sea auditable.",
    auto_6ed63fc9cfbb: "Ligando no registrado en esta corrida",
    auto_5cc2fcbbbc9d: "Lipinski no calculado para este análogo",
    auto_52e9ae29fb89: "Lipinski pasado — cumple reglas de drug-likeness",
    auto_2e5a9badd398: "Lo que escribas saldrá de tu máquina hacia",
    auto_a10f57b88037: "Lo que se acopló",
    auto_8b8d19d6a005: "LogP describe la distribución calculada entre fases acuosa y lipídica. Es un descriptor dependiente del método y del estado químico; no predice por sí solo permeabilidad, circulación ni eficacia.",
    auto_0310df6f0be2: "LogS es una estimación o medición expresada en escala logarítmica según el método usado. Los rangos orientativos no sustituyen un ensayo de solubilidad en condiciones experimentales.",
    auto_cd20267c5ed3: "Los PAINS son falsos positivos frecuentes en ensayos biologicos (Baell & Holloway, 2010). Se recomienda validación experimental exhaustiva antes de considerar esta molécula como hit.",
    auto_e0d54255ddee: "Los receptores compartidos no están disponibles.",
    auto_aca2756d969d: "máquina virtual o sin GPU— y bloquea el avance de la corrida mientras",
    auto_917ac7093911: "más",
    auto_ec0377945f92: "Masa de la molécula expresada en daltons. El umbral de 500 Da es una regla empírica de Lipinski para comparar series; no garantiza absorción ni exposición en una persona.",
    auto_f63ac70bacae: "Máximo — utiliza la mayor parte de tu CPU. Cierra otras aplicaciones pesadas",
    auto_a9b6fb847654: "Mayor proporción sp³ — descriptor de complejidad",
    auto_2528775f013b: "Media geométrica de tres factores derivados de ADMET-AI: solubilidad, absorción intestinal y un término de toxicidad basado en la probabilidad de bloqueo de hERG. Las constantes que los combinan están elegidas a mano y no ajustadas contra datos clínicos. Sirve para priorizar dentro de una serie y para ver qué término penaliza a una molécula; no es un pronóstico de si sobrevive en sangre. En particular no incorpora el margen Cmax libre / IC50, que es lo que decide el riesgo real de hERG.",
    auto_00dbdddcb460: "Memo opcional con hashes y metadatos técnicos de un dossier. Prueba integridad y fecha de emisión, no autoría, validez científica ni propiedad intelectual.",
    auto_b76b56f0f66f: "Memo opcional que registra hashes y metadatos técnicos de un dossier. Puede probar qué bytes se asociaron a una fecha y transacción; no valida la ciencia, no certifica autoría y no sustituye la procedencia local.",
    auto_a6c6215f575a: "método no registrado",
    auto_29f1a0264265: "Mide qué tan enfocada está la molécula en los Hotspots de la proteína.",
    auto_ed5c43cd041b: "Mismo receptor y misma corrida; se muestran las coordenadas SDF reales de las poses #",
    auto_530df92bc823: "Modelo tabular opcional para cohortes y pesos declarados por un perfil. No diagnostica toxicidad ni identifica patentes por sí mismo.",
    auto_605672b1cc3b: "Modelo tabular opcional para experimentos concretos. Sólo debe mostrarse cuando el manifiesto declara sus pesos, cohorte y aplicabilidad; no detecta patentes ni diagnostica toxicidad por sí mismo.",
    auto_3c11e2b8db88: "Modelo ultraligero ideal para PCs sin GPU y recursos muy limitados.",
    auto_c9284334afff: "Modelos D-MPNN que producen señales sobre absorción, permeabilidad y otros endpoints. Se interpretan como predicciones computacionales, no como seguridad clínica.",
    auto_bdfddc5eef10: "Modelos de aprendizaje automático que producen señales sobre absorción, permeabilidad, unión a proteínas y otros endpoints. El índice de perfil sanguíneo es heurístico y sirve para comparar una serie; no es un pronóstico clínico ni una decisión de seguridad.",
    auto_4e5f58ee4e09: "Modo offline: activar modo web para enriquecer con PubChem/ChEMBL",
    auto_a3fa6f75da44: "Modo web activo: enriquece con PubChem/ChEMBL y puede tardar más",
    auto_ca4cf793bc42: "Módulo experimental. Se ejecuta EN LOCAL, en esta máquina: la primera",
    auto_a4e3d3490896: "Módulos de IA y Física",
    auto_6be8b77110ff: "MolChat está respondiendo...",
    auto_144067985189: "Mostrar el receptor completo",
    auto_5ebc24194e17: "Motor de docking empírico que explora poses dentro de una caja y devuelve un score de Vina. Ese score sirve para ordenar poses bajo el protocolo declarado; no es una energía libre experimental ni una garantía de afinidad.",
    auto_2e24a6f6267b: "Motor de docking estándar. Exhaustiveness=8. ~20s por ligando.",
    auto_d64c24cabf94: "Ni éxitos ni fracasos: describen el terreno o declaran la apuesta antes de mirar.",
    auto_46c73e4fa1e0: "Ningún caso coincide con la búsqueda.",
    auto_f3beed6bd3c8: "No cierres el caso sin copiarlo o reintentar el guardado.",
    auto_1e6cb1e6dc11: "no contiene un",
    auto_271fb52e9981: "No hay analogos para comparar. Evalua mas moleculas contra este target.",
    auto_0e26df2c1c3d: "No hay contexto molecular adjunto.",
    auto_c922a83946da: "No hay metales declarados para conservar",
    auto_2159b50010ad: "No hay targets compartidos aún",
    auto_ade812f7939a: "No hay una molécula adjunta. Puedes pegar datos en tu mensaje.",
    auto_47083d99db42: "no se calculó",
    auto_632d94f6b658: "No se generó un ligando acoplable",
    auto_fafd22a23afe: "No se pudo cargar el visor 3D científico (Mol*).",
    auto_ce72cf899871: "No se pudo comprobar si el ranking del motor está respaldado para",
    auto_02aba466e282: "No se pudo conectar con la comunidad. Verifica tu conexión a internet.",
    auto_129fd24eafd6: "No se pudo crear el caso. Revisa el aviso de arriba: puede haber un cambio sin guardar en el caso actual.",
    auto_34d105ded9d6: "No se pudo crear la variante.",
    auto_96129f3bbb7a: "No se pudo exportar el paquete:",
    auto_b2869e46ca45: "no se pudo mover y sigue en la cuenta invitada; sus resultados ya son tuyos.",
    auto_f56cc2a1ae4e: "No se pudo traspasar:",
    auto_7d87ae35f871: "No se registró un snapshot content-addressed para esta corrida.",
    auto_da60d4d5d247: "Número de átomos aceptores según la representación química. HBA ≤ 10 es un criterio de Lipinski para comparar compuestos, no una garantía de absorción oral.",
    auto_062fc71dfbbf: "Número de enlaces rotables definido por el descriptor. Valores altos pueden asociarse con mayor flexibilidad conformacional, pero no prueban inestabilidad ni impiden el acoplamiento.",
    auto_1e01fec6e93b: "Número de grupos capaces de donar hidrógeno según la representación química. HBD ≤ 5 es un criterio de Lipinski para comparar compuestos, no una garantía de absorción oral.",
    auto_2f66c748dbd5: "Número total de colisiones e interacciones atómicas íntimas. Fuerte indicador de encaje espacial.",
    auto_174b86a69af7: "Número total de contactos en la primera y segunda esfera de solvatación del bolsillo.",
    auto_519ddde05991: "O continúa con",
    auto_7a2d6cf4994c: "Ocultar el receptor (dejar solo sitio activo + grid)",
    auto_b0487918dd42: "Ocultar la molécula (ligando acoplado)",
    auto_eef39378ea52: "Ocultar las líneas de interacción (H-bonds, hidrofóbicos...)",
    auto_f08ea8842a9f: "ocurre. NO es necesario para el docking: apagado, el acoplamiento y",
    auto_67bfa12d71a2: "Ocurrió un error inesperado al subir el receptor.",
    auto_e57566562d4e: "Ocurrio un error inesperado en este componente.",
    auto_ea5a09df6c44: "OH; H-bonds, geometría restringida por el metilo.",
    auto_98c1ad5d0471: "Onda radial matemáticamente sincronizada con la activación de los módulos.",
    auto_d1728e225254: "órdenes de magnitud, derivado del score con ±",
    auto_1f9342007908: "Par compatible con un puente de hidrógeno, pero ECIF cuenta contactos dentro de un radio de corte: no comprueba geometría ni ángulo.",
    auto_7080a733bfcd: "Par donador-aceptor compatible con puente de hidrógeno, contado por distancia y sin geometría.",
    auto_fe965110a196: "Par donador-aceptor compatible con puente de hidrógeno. ECIF lo cuenta por distancia, sin verificar el ángulo D-H⋯A.",
    auto_f2cfe47391ae: "Parámetros del motor no registrados",
    auto_ad2f27e22451: "Pares entre átomos de carbono alifático del ligando y oxígenos del bolsillo. Captura interacciones dipolo-dipolo y puentes de H con aceptores.",
    auto_2def3ff0a99f: "Parte de",
    auto_c025cd216bcf: "Pausar la simulación",
    auto_b3db787af1a3: "Penalizaciones comunes: Peso > 500 Da, LogP > 5, más de 10 rotaciones.",
    auto_4a460dbb24e9: "Por favor, dale un nombre a tu receptor.",
    auto_b612f6dc223e: "Por favor, selecciona un objetivo biológico (Target) del catálogo antes de iniciar la simulación.",
    auto_f4fdb640f385: "porque la molécula haya dado un resultado desfavorable. El resto de la evaluación —acoplamiento, poses y controles físicos— no depende de este bloque.",
    auto_17a9283c624b: "PPB es una categoría derivada de un modelo o descriptor. La fracción libre depende de concentración, matriz y condiciones; no basta para concluir distribución o actividad.",
    auto_38997db9a692: "Predicción de solubilidad, absorción intestinal, BBB, unión a proteínas plasmáticas",
    auto_9d931f7fadb2: "predicción farmacocinética en vez de mostrar una inventada.",
    auto_32a9d49fe4e0: "Pregunta sobre evidencia estructural",
    auto_16f46113d69c: "Pregunta sobre la molécula adjunta",
    auto_df93272641f2: "Preguntas con criterio de aceptación declarado antes, que lo superaron.",
    auto_9385e5fdcc30: "Prepara hipótesis moleculares, explora poses y documenta la evidencia computacional de cada corrida.",
    auto_7f97a774bf43: "Procedencia de las señales ·",
    auto_f5681aafed47: "Propiedad físico-química extraída del complejo molecular.",
    auto_129ae70d08f8: "Prueba el visor ligero desde el botón del visor: necesita bastante menos del equipo.",
    auto_03d50be324c8: "Puedes introducir el PDB ID manualmente.",
    auto_5bdde6ca20b7: "Punto de entrada al acelerador. Soporta ingesta masiva en lotes (CSV/SDF) o cadenas individuales. Tokenización inmediata para el pipeline de validación.",
    auto_a0adb4d99412: "QED combina varios descriptores en una escala histórica de drug-likeness. Un valor alto indica cercanía a esa heurística, no aprobación, seguridad ni similitud causal con fármacos.",
    auto_842dd575a113: "que no está instalado localmente.",
    auto_abd7ce809ba9: "Qwen2.5-1.5B servido localmente cuando el modelo está instalado. Puede consultar evidencia persistida y explicar estados, pero no es la fuente primaria de resultados, no implica voz local y funciona sin red sólo después de descargar el modelo.",
    auto_afc96853778b: "Rango de scores entre poses",
    auto_dabe6e993bad: "Razonamiento científico más avanzado, requiere mejor procesador/RAM.",
    auto_38522fe5e383: "Red neuronal de grafos para producir una señal de rescoring cuando el modelo, sus pesos y su cohorte están declarados. Las métricas y cualquier afirmación sobre sesgo dependen de la partición y el benchmark concretos; no se generalizan a todas las moléculas.",
    auto_00cf99ca43b6: "REDUCE la afinidad predicha",
    auto_4a70388e7d39: "Regla de los 5 de Lipinski",
    auto_3db8386c07e1: "Reglas de Veber",
    auto_932951364a43: "Regresión o clasificación sobre features de una pose cuando existe un perfil y dominio de aplicabilidad válidos. Su salida es una interpretación derivada; no sustituye el score observado de Vina fuera de dominio.",
    auto_c1f4fae31eb5: "Regresión sobre features de pose cuando existe un perfil y dominio válidos. La salida es una interpretación derivada, no una corrección universal de Vina.",
    auto_3363d78ec95f: "Reminimiza la pose real del acoplamiento con OpenMM y resta receptor y ligando aislados. Sirve para",
    auto_7b77d6194b7b: "Reproducir la simulación",
    auto_000b59c99346: "Rescoring derivado de features de la pose cuando el perfil y su dominio están disponibles. La salida puede expresarse en pKi y kcal equivalentes según el protocolo; fuera de dominio prevalece la observación de Vina.",
    auto_d7714baeba50: "Residuo del sitio activo.",
    auto_0216bf13df20: "Residuo pequeño, contribuye al empaquetamiento hidrofóbico del bolsillo.",
    auto_3b64bc4ca408: "Revisión de alertas",
    auto_1e917b222b05: "Rígida; define giros, contribuye a la forma del sitio.",
    auto_ccc606b7ab22: "Ro5 de Lipinski:",
    auto_a0f1490a20d0: "s",
    auto_73ce5e0c984a: "Salir de la etapa",
    auto_6a23e1f9d80d: "Score de docking del mejor pose de AutoDock Vina. Un SHAP positivo indica que poses más afines empujan el score del modelo hacia arriba.",
    auto_e930067de091: "Se eligió el tautómero canónico de RDKit",
    auto_4750b49f870b: "Se está descargando...",
    auto_69c1421c8782: "Se protonó a pH",
    auto_51a229f168ca: "Selecciona una evaluación persistida para consultar moléculas comparables contra el mismo receptor. No se muestran ejemplos ni resultados simulados.",
    auto_6f82b47554ca: "SELECCIONADO PARA COMPARAR",
    auto_5a961ba823b3: "Sello anterior al registro de procedencia: no consta qué corrida certificó.",
    auto_652200f9cc43: "SELLO SIN CORRIDA",
    auto_b75d71d7c486: "señal",
    auto_ff7cabb9c513: "Señal · warheads de zinc (UMS, SMARTS):",
    auto_cf041ff07895: "Señal computacional de permeabilidad a BBB. No demuestra entrada al cerebro en vivo ni implica beneficio o riesgo terapéutico.",
    auto_30f8b7d8b9a8: "Señal computacional de permeabilidad o absorción intestinal. Su resultado depende del modelo y de su dominio; no predice por sí solo exposición humana.",
    auto_20ba0016e1e3: "Señal neuronal de grafos disponible sólo para perfiles que declaran modelo, pesos y cohorte. Las métricas son condicionales al benchmark; no se presenta como detector universal de sesgo o termodinámica.",
    auto_9340a078aa31: "Sí, borrar datos",
    auto_1351ada0b9c9: "SIN ALERTA",
    auto_806a2dd2c630: "Sin cadena lateral; permite espacios estrechos en el bolsillo.",
    auto_440fc8f92285: "Sin carpeta elegida.",
    auto_17ecdaf55d49: "Sin caso",
    auto_280145ccad5c: "sin clasificar — trátalo como no verificado",
    auto_85e292a64f4e: "Sin comparación",
    auto_185e750ee009: "sin dato",
    auto_01f70610d0a7: "sin dato en esta corrida",
    auto_94135ee04adb: "Sin GPU — CPU:",
    auto_14009a618e8d: "sin ID",
    auto_a9b0c58ab88e: "SIN ÍNDICE",
    auto_fe9905aee429: "Sin interacciones: ejecuta la evaluación para analizar los contactos del ligando",
    auto_abcb7f140cae: "Sin molécula: ejecuta la evaluación para ver el ligando acoplado",
    auto_310c64678aed: "sin resultado",
    auto_1ce84036ee8b: "Sin resultados para esta búsqueda",
    auto_09e250071934: "Smart sampling, 2-3× más rápido que Vina. Misma precisión.",
    auto_396af15df54e: "Snapshot content-addressed conservado; la ruta local permanece privada.",
    auto_e66cbf48ffa4: "su identificador para poder recuperarla con la sesión correcta.",
    auto_f78181f943ab: "Subí un target público para colaborar con la comunidad.",
    auto_1b72f46cf978: "sus puntuaciones se calculan igual, y el panel de Parámetros queda sin",
    auto_a3f6d7df9f9f: "Tamaño de la caja (Å)",
    auto_faa74cbc60a9: "También se adjunta el contexto molecular disponible.",
    auto_3e3117216cff: "Target sin nombre",
    auto_b5dacc17359a: "Tiol; puede formar enlaces covalentes con warheads electrofílicos.",
    auto_da7c1fdae98a: "Todavía no hay casos.",
    auto_7cbf8c0d5ae1: "TPSA resume la superficie polar topológica. Los umbrales de Lipinski y Veber son orientativos y deben interpretarse junto con el resto del perfil; no determinan el paso celular o cerebral.",
    auto_c224ef74ad87: "Tu identidad molecular se está validando en el servidor local.",
    auto_7d5211dfd7ca: "Tu sesión cambió. El resultado visible se limpió, pero la corrida terminada conserva",
    auto_d63f7a54d93b: "Tu sesión cambió. Los resultados anteriores se limpiaron para evitar guardar moléculas de otra cuenta.",
    auto_b0a87dfd9e6e: "Tu sesión cambió. Los resultados anteriores se limpiaron para no mezclarlos con otra",
    auto_e5d485629017: "Umbral de afinidad",
    auto_c0f7ffa788c9: "un modelo",
    auto_0640a1e7f589: "Una alerta PAINS, una heurística SA u otra regla requiere revisión. Se conserva como evidencia y no se convierte automáticamente en toxicidad o descarte.",
    auto_fff211e08ae8: "Una anti-diana no se evaluó",
    auto_4afeaaad596e: "Valida la estructura, la valencia, la quiralidad, los conformeros y propiedades fisicoquímicas. Estas señales ayudan a revisar una entrada; no determinan por sí solas viabilidad clínica ni si una molécula es un fármaco.",
    auto_05b7cb91f92b: "Valida sanitización, valencias, aromaticidad y representaciones moleculares. Las señales se conservan para revisión; no decide por sí solo la viabilidad del compuesto.",
    auto_317bd150cc87: "Valida valencias, quiralidad, conformeros y descriptores fisicoquímicos. Sus señales sirven para revisar una estructura; no determinan por sí solas si es un fármaco.",
    auto_f1f215ef3d12: "Varianza entre poses",
    auto_b296de8883ee: "Veber relaciona enlaces rotables y TPSA con biodisponibilidad oral en ciertos conjuntos. Es una heurística de priorización, no una predicción individual de biodisponibilidad.",
    auto_e5d668feb775: "Ver la molécula (ligando acoplado)",
    auto_1054995e158b: "Ver las líneas de interacción (H-bonds, hidrofóbicos...)",
    auto_2e80694bf926: "Ver por qué requiere revisión",
    auto_fa699172d465: "Visualizando la topología secuencial completa.",
    auto_dc96db7f7404: "Vuelve a comprobar la preparación antes de ejecutar.",
    auto_faf5a356627c: "y esta ficha muestra",
    auto_72ef951a4533: "ya está registrado en",
  },
  en: {
    auto_5bcd0dc46b99: "— outside the applicability domain; it is shown as a reference, not as a prediction.",
    auto_c8b9d71daaca: "— information, with a weight of 0 in the ranking",
    auto_e3213d2976ba: "— the race did not register if it fell within the domain of applicability.",
    auto_988351833ce1: "— Ranched by score",
    auto_99b5f43f6422: ", so there is no report to open. Identifier is still saved:",
    auto_8ff2cb920103: ", none with saved result yet",
    auto_5bab61eb5317: "♪ Oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh.",
    auto_cc3fb7ae5b1e: ". The folder you have chosen is",
    auto_dc0b31771c0b: ". The folded structure is preserved as evidence, without affinity.",
    auto_a0c51a5fc4c9: ". The numbers of each tab are read from the manifest in each build: the prose cannot deviate from them without notice. An experiment sealed after that date is not yet here.",
    auto_3cbb86a7ea90: "Nothing moved; you can try again.",
    auto_ea64cf436cb0: "You can take it to your account now. It moves, it doesn't copy: it will stop being on the guest account.",
    auto_a6cdeb7c5844: "No API key.",
    auto_d970f808cba3: ". It only exists in memory:",
    auto_655a8de817b6: "· legacy signals available only as a technical trace",
    auto_73e38ad50e54: "· not authorised",
    auto_d524488efd51: "· Commercial use with separate license",
    auto_7a133b421d46: "(function(){ try { var auth = JSON.parse(localStorage.getItem(\"moldesign_auth\")  \"null\"); var userId = auth  auth.user  auth.user.user_id; var saved = userId ? localStorage.getItem(\"moldesign_theme:user:\" + userId) : null; if (saved=== \"light\") { documentElement.classList.remove(\"dark\"); document.documentElement.classList.add(\"light\"); } } catch(e) }();",
    auto_4d382c8b0332: "(function(){ var s = document.createElement('script'); s.src = '/3Dmol-min.js'; s.onerror = function(){ console.warn('[MolDesign] 3Dmol-min.js not found in /public/. 3D display not available. Reinstall app or run npm run dev.'); }; document.head.appendChild(s); }();",
    auto_0ce6ec21b144: ") not used — cpp-python flame without CUDA",
    auto_1765f4131521: ") and creates a new private receptor. The original does not change.",
    auto_d45dcd15ff99: ") The result is supported by the signs that did, with the renormalized weights that appear on each card. The description of the family and its note below continue to describe the design, not what happened here.",
    auto_5c7c8c2f3b8e: ") The above verdict was calculated without them, so it can be optimistic.",
    auto_1358197dcf7b: "× docking time. Expands geometric coverage; does not improve the choice of the top-1 pose by itself.",
    auto_6dbd2d03ab5b: "• Positive contribution in this model",
    auto_2d325f1fbc1d: "▼ Negative contribution to this model",
    auto_c4bcead81aba: "✓ Positive sign",
    auto_3963e4218261: "• Negative signal",
    auto_7167a3bad96d: "in favour of the main target, for the dispersion of ±",
    auto_1f88e3bba8e6: "Open without optional modules",
    auto_4d2183484683: "Open a sample the result that produced that run; it does not replace the evaluation you have on screen or run anything again.",
    auto_ad4e898dd924: "Intestinal absorption, permeability BBB, PPB, LogS solubility and reactivity alerts, with ADMET-AI (Chemprop D-MPNN). The consensus of BBB is 39 of 41 passive diffusion drugs in a regression cohort of 46, without independent holdout: it is the figure with which it was adjusted, not an external validation. The blood profile index is heuristic.",
    auto_0d82ae16ddd4: "Hydrogen Bond Acceptors (HBA)",
    auto_b12bc4e545ec: "Docking against the 5 panel anti-targets (ANTI_TARGET_PANEL): hERG/KCNH2 5VA1 (cardiotoxicity), CYP3A4 4NY4 (interactions), 5-HT2B 4NC3 (valvulopathy), PDE3A 1SO2, NaV1.5/SCN5A 6MVW (cardiac conduction).",
    auto_29368dd6d018: "ADME collects computational signals of absorption, distribution, metabolism, and excretion. This index serves to compare molecules within the protocol; it does not predict by itself how a person will respond.",
    auto_2ab36069225c: "ADMET-AI did not run in this run",
    auto_6cb48f8ad846: "generation warning(s); consult the dossier for detail.",
    auto_73dfe1bf7b4c: "Affinity (docking score)",
    auto_5542e5a19746: "UMBRAL ALERT",
    auto_6b882e73c6d3: "Off-Target Alert(s) Overrun",
    auto_0ec637ca2747: "AlphaFold-Multimer for protein-peptide complexes.",
    auto_f3837875dab4: "High — complies with most of these heuristic rules",
    auto_5fd84e29ad40: "Longer Amida; H-bonds donor and acceptor.",
    auto_062164e36e14: "Amida; donor and acceptor of H-bonds.",
    auto_20974a2a67a6: "Amino (+); salt bridge with acidic ligands, cation-đ.",
    auto_54ecc2e4a2ee: "Aromatic ring; interactions with aromatic ligands.",
    auto_98d8f5a99754: "Topological Polar Surface Area (TPSA)",
    auto_11bdeb08e4bf: "Research artifact to represent protein–ligando contacts. It is not presented as a physical verifier or as an available engine if its dependencies or weights are not present in this installation.",
    auto_0fbfc17c9782: "Experimental recoring artefact representing contacts of a pose. It does not automatically emit Kd/Ki in this installation nor validate geometry by itself.",
    auto_7520b27b9116: "Experimental artefact that represents protein–ligand contacts. It does not validate geometry alone nor emit Kd/Ki in this installation.",
    auto_d0b584a74983: "assigns weight by design",
    auto_b6be6414756b: "Optional assistant with local Qwen2.5-1.5B that consults persistent evidence and helps explain it. It is not primary source of results; it requires the installed model and does not include local voice in this runtime.",
    auto_7f2537d04d9e: "atom(s) with ESMFold coordinates and",
    auto_808cfa7d641c: "Protein atoms",
    auto_ba93a478fc9b: "INCREASE the predicted affinity",
    auto_2f68d2558c76: "AutoDock Vina 1.2.7 explores poses within the declared box and returns an empirical score to order poses. It is not experimental free energy.",
    auto_84d405785c17: "Sulphur on the side chain; you can make S-đ or S-H contacts.",
    auto_32e8785f56fe: "Low — several heuristic rules are not met",
    auto_324dd8981c4f: "Balanced — good performance without slowing down equipment",
    auto_1856b6561e91: "Each dimension of the box should be between 5 and 80 Å.",
    auto_f4940abeb43f: "Branched side chain; van der Waals contacts with lipophilic ligands.",
    auto_68483034f561: "Calculates descriptors and drug-likeness rules to contextualize the structure. It does not guarantee absorption, safety or oral viability.",
    auto_1da2cfab4f02: "Calculating with OpenMM... (",
    auto_aa7e38e37678: "Cancelled by the user",
    auto_04230d165336: "Carboxylate (−); ion/sal bridge, H-bond strong aptor.",
    auto_9559239a0af7: "Carboxylate (−); salt bridge, cations recognition.",
    auto_443a6fd91b4e: "model load can take several minutes — especially in a",
    auto_56307dd72ba4: "Ionic charges and hydrogen bonds",
    auto_1daed134ce8c: "Box centre (Å)",
    auto_36049ba7faf6: "Proximity between ligand donor nitrogens and pocket carbons. It is NOT a hydrogen bond: carbon does not have lone pairs or the electronegativity to accept it. It measures packing and polarization.",
    auto_09f5a9e4d304: "Close between ligand-donating oxygens and pocket carbons. It is NOT a hydrogen bond, for the same reason: carbon does not accept. Measure packaging.",
    auto_416ef02a1420: "Entry coverage:",
    auto_f2422134496a: "Partition coefficient (LogP)",
    auto_9835328903b8: "Comparison of properties between",
    auto_aa8a3c091711: "Complete the name, string and six coordinates.",
    auto_c0a10228aed3: "completed(s) with",
    auto_7417a14c6944: "Check geometry, shocks, connectivity and interactions under the available controls. RMSD is interpretable only when there is a compatible reference.",
    auto_b1f6e510eb0f: "with",
    auto_f24ed0ca4042: "with result",
    auto_121e3999ff64: "with your local account",
    auto_0229a5139372: "Connect to see shared targets",
    auto_fb21ded85274: "Conservative — does not overload CPU",
    auto_146267f4301a: "Frequent hydrophobic contact in junction pockets.",
    auto_932e50554e31: "Atomic contacts with phosphate groups.",
    auto_dc3304d88376: "Atomic contacts between Carbons and Nitrogens.",
    auto_608b11c2a2f3: "Atomic contacts between Carbons and Oxygens.",
    auto_83a92d919084: "Long-range contacts on the edge of the solvent or outer protein surface.",
    auto_5bcb436809b0: "Medium-range contacts between Carbons and Oxygens.",
    auto_4b4916d3dc86: "Hydrophobic contacts between ligand carbon atoms and protein.",
    auto_c359f0cd7a14: "Conformation count not registered",
    auto_01a2c44be46f: "against this same receptor.",
    auto_d8233986780e: "Physical pose controls",
    auto_f1037aec2a80: "Copy Solana address",
    auto_262949a66911: "Cumulation pending registration",
    auto_0ef026dc501a: "Polar clearance cost (Generalized Born)",
    auto_ce0ad0ebf48a: "Create another case to evaluate a different structural system.",
    auto_8cd782f9aaaa: "Acceptance criterion declared before, and fulfilled.",
    auto_9eca858843aa: "It crosses only the signs that the profile declares and that the run produced. It retains observation, derivative score, applicability and abstention; it does not amount to universal consensus or an experimental conclusion.",
    auto_9d0f79ed0388: "account, but the run remains identified: restore the session and use \"Retry tracking\".",
    auto_600ccd1b7156: "of",
    auto_c1b398a5da7e: "of sealing invalidated the figures of this record.",
    auto_c5324603beef: "Atomic density in the extended bond cavity.",
    auto_b099e128531e: "Atomic density in a specific three-dimensional ring.",
    auto_481656be8588: "Carbon density around the ligand in the average distance range of 4 to 8 Ångströms.",
    auto_2e8b40078ffb: "Nitrogen density interacting strongly at less than 4 Ångströms.",
    auto_d5586e61a936: "Oxygen density in an intermediate range around the ligand.",
    auto_5b09d65f54ac: "Density of carbon-nitrogen pairs in intimate contact (< 4 Å). It can reflect implicit H bridges or nearby polar packaging.",
    auto_bea13b26dbec: "Oxygen-Carbon pair density at the edge of the solvent (8-10 Å). It contributes to the long-range stereo context.",
    auto_9a3561c18fde: "inside Lipinski",
    auto_4696a2a82a01: "inside Veber",
    auto_0e4b9698dddb: "within the threshold",
    auto_b35a21592ba5: "Descriptor 1D/2D of ligand. The heavier molecules can correlate with systematic changes in the score of the model.",
    auto_54dd883d2597: "Descriptors of GFN2-xTB (tight-binding, gap HOMO-LUMO, energy) and MMFF94, ~0.1 s/mol. The aggregate index produced is a linear combination with hand-picked weights: informs and saves, but from 2026-09-04 does not enter the main score. It is not equivalent to GAFF2 or a DFT calculation.",
    auto_a8e7405da2c4: "since the run",
    auto_a2f32be1b030: "Breakdown of Pharmacophores",
    auto_318b7c221101: "It detects functional groups candidates to coordinate zinc from the chemical structure, without executing docking. It is a protocol signal for specific M5-Zn profiles; it is not a quantum calculation or a general conclusion of activity.",
    auto_6b74eaabc080: "SMARTS detector of functional groups that are candidates for metal coordination. It is only integrated using accurate M5-Zn profiles; its state, components and applicability are shown without manufacturing a formula out of profile.",
    auto_e53d65c119b2: "Not available: this installation does not include local voice recognition",
    auto_1416d9865ffd: "Dictating by voice with the local model",
    auto_d2b216252962: "Difference between the best and worst pose of docking. Indicates how discriminant the score is in the sampled conformational space.",
    auto_9331807fc431: "SE(3)-equivariant diffusion (Baker Lab). GPU required.",
    auto_408d39d8cace: "Family design:",
    auto_c56fdd911c69: "Dispersion of the affinities between the poses generated. A high variance suggests an ambiguous pocket with multiple binding modes.",
    auto_15390043b6c6: "Local Docking inside the declared box. Explore poses and return an empirical score of Vina; it does not affirm a thermodynamically optimal pose or an experimental free energy.",
    auto_411c9577cc23: "Hydrogen Bond Donors (HBD)",
    auto_d59e25441a19: "Long-range conformational and sterical effects exerted by pocket carbons.",
    auto_91d8ff3aff6a: "The pose file does not contain the two selected poses. The run is preserved without replacing your data.",
    auto_9efee153557b: "The case was released; you can try to follow up later.",
    auto_4bf26aa090e9: "The molecular context available is attached to each shift.",
    auto_5e8ef3521b05: "The dossier could not be generated.",
    auto_b3945ccefff7: "The report is available, but this case does not retain a verifiable footprint of executed inputs.",
    auto_b0407faa7b48: "The engine is preparing. The evaluation will be available as soon as it responds.",
    auto_74f10d125232: "The local engine is finishing to start. Retrying automatically...",
    auto_4b66d3c2fe33: "Username is mandatory.",
    auto_1171a79e25ba: "The profile is calculated and saved with the run: it appears in",
    auto_f0d9b3df714d: "The pH used is written in the file.",
    auto_225f4287b89f: "The pipeline is running the background panel; the result will appear automatically.",
    auto_8819735dd62d: "The receptor is fixed by the first run of this case.",
    auto_dae68ac9b41e: "The result can continue to exist: this says that it has not been read right now, not lost.",
    auto_8a59609e15c0: "score as evidence of affinity.",
    auto_3a94369c8527: "Vina score is an empirical scoring function, not a measured free energy, and its dispersion against experimental affinities is about ±",
    auto_383ad4c4bf5b: "Vina's score orders poses under the declared protocol. It serves as an empirical sign of relative affinity; it is not an experimental measurement of free energy or activity.",
    auto_f772d2e3af48: "The 3D viewer is not available on this computer.",
    auto_4356059ccdf0: "The scientific viewer (Mol*) could not start on this team.",
    auto_32983b1d7ac2: "Email and password are mandatory.",
    auto_703e06c21c31: "In ideal conditions at 298 K, a difference of 8 kcal/mol implies a thermodynamic ratio of approximately 10^5–10^6; Vina does not directly measure that free energy.",
    auto_1efcd5b46d53: "on this team, though «",
    auto_324033e95c09: "In manual mode you must provide the coordinates (X, Y, Z) of the center of the active site.",
    auto_f459de5d43b3: "On a virtual machine, enabling the hypervisor's virtualized GPU can solve it.",
    auto_0a42461c773d: "Error loading coordinates in the display.",
    auto_15eff5b3b975: "Failed to load report",
    auto_090a83af1bac: "Error without message.",
    auto_09cd68a2a77b: "It's",
    auto_c4bbdea3891b: "It's",
    auto_9debabbaa01a: "EN",
    auto_6982bfeae501: "It's because",
    auto_91249e5adbba: "es-ES",
    auto_e5274e78712c: "es-MX",
    auto_a187157bca8f: "Scalability of Pipeline",
    auto_14578be07d4d: "ESMFold is operational for folding; conversion to a dockable ligand is not yet supported, so the docking is not evaluated.",
    auto_4cce270ad33f: "Specificity of Diana",
    auto_946f5d999b58: "Specific family",
    auto_9a8c2888bccd: "This run has no pharmacokinetic prediction: ADMET-AI did not run, either because it was disabled in the options of the run or because the model could not be loaded on this computer. The fields below are empty because nothing was measured,",
    auto_28590748cd34: "This account has not yet authorized such a destination.",
    auto_bf1431bba866: "This function requires",
    auto_57652532d30f: "This molecule belongs to another account. Log in with the account you evaluated it for storage in your MolDex.",
    auto_265b259a1293: "This case has a complete run, but",
    auto_248db3e9f594: "This team exposes 3D, but not with what Mol* needs to draw.",
    auto_49e5b55bba06: "This panel was executed but could not be written in the evaluation: if you change tab you lose it, and the report will say that no anti-target was registered.",
    auto_dbfb7d741250: "this receptor. It treats the result as a hypothesis: do not cite",
    auto_e68b364d222e: "Estimates a ΔG MM-GBSA over the selected pose",
    auto_dc39d5d9367f: "Post-hoc estimate of ΔG with MM-GBSA and implicit solvent (OpenMM OBC2)",
    auto_bf0382f209fa: "Evaluate against 5 safety receptors (hERG, CYP3A4, 5-HT2B, PDE3A, NaV1.5)",
    auto_15eb472d4323: "Evaluate if your molecule complies with historical rules to be a good oral pill.",
    auto_0d93be49ed45: "Audit evidence",
    auto_7786e423c133: "Excellent balance between speed and local scientific reasoning.",
    auto_7c3ae9bd54e6: "The value in at least one of the two molecules is missing",
    auto_fdcf2203371a: "Phenol; π-stacking + H-bond donor/acceptor by OH.",
    auto_a2b452f155f4: "Sealed record sheet",
    auto_b05b976cbc9e: "outside Lipinski",
    auto_715e0e63b8f6: "outside Veber",
    auto_2ccc163e69dd: "outside the threshold",
    auto_ce040e015442: "GB). To be used when loading.",
    auto_8ccbd006d5fd: "It generates plausible 3D conformations by geometric restrictions and stochastic sampling. It does not demonstrate that a conformation is dominant in solution.",
    auto_e1592998873b: "Generates data with",
    auto_0c7048843eda: "It generates a PDF with the evidence and its verifiable identifiers. It can include an integrity link to Solana when the user requests it; it does not transfer the ownership of the molecule, the case, or its results.",
    auto_65299f4a07a8: "Manage simulation modules",
    auto_24300640c524: "GFN2-xTB, semi-empiric tight-binding — not DFT. Calculate HOMO/LUMO, dipolar moment, partial charges and polarizability in ~0.1 s/mol. It is not equivalent to GAFF2: they are different force fields and no correspondence has been measured here. The aggregate index it produces is heuristic and since 2026-09-04 does not enter the main score.",
    auto_887c159b9e2f: "SMILES Graph preserved;",
    auto_4c9d11deb414: "Local graph in SQLite and FTS5 that organizes molecules, targets, evaluations and evidence for MolChat to consult persistent facts. Improves the recovered context, but does not guarantee zero hallucinations or replace scientific validation.",
    auto_f12bbb9518b1: "Guanidinium (+); strong salt bridge, phosphate recognition.",
    auto_7f0c5ddda6e9: "There is recoverable evidence of a PREVIOUS run: inputs have changed since it was executed.",
    auto_90ca0c04628c: "Tool available for explicitly configured preparation and minimization operations. MolDesign does not execute production molecular dynamics or FEP with this component.",
    auto_d9d584c1546b: "Tool available for explicitly configured preparation or minimization operations. MolDesign does not run production MD or FEP with it.",
    auto_b8c87de15d58: "Local tool with public source code to prepare, evaluate and document reproducible and auditable structural evidence.",
    auto_f288a26eee67: "Heuristic synthetic accessibility (1–10). It is an indicative signal about molecular complexity, not a price or guarantee that synthesis is possible.",
    auto_2aac960c125c: "Hydrophobic; defines the shape of the pocket.",
    auto_cb3645865abe: "Hypothesis of one's own put to the test and knocked down, from here came almost everything learned.",
    auto_6c6d4fcf3374: "There was an error in the discharge.",
    auto_fa14698a6e5a: "Own ideas put to the test and refuted. From here came almost everything learned.",
    auto_eeb11cc0b66e: "Language of dictation: Spanish",
    auto_dda6b46d3faf: "Language of dictation: English",
    auto_c1b0533bca64: "Log in cloud to share with attribution.",
    auto_3c658efb0bdc: "Log in to save molecules to your MolDex. Saving requires an account to associate the molecule to your profile.",
    auto_f56a50a80039: "Log in to save molecules in your MolDex. Your session expired or is not active.",
    auto_7194e52d2e3f: "Install only what you need. Each file is checked using SHA-256 before being available for MolDesign.",
    auto_df4742f77e88: "Optional integration that records a technical hash and metadata in a public memo. It can verify integrity and date of issue; it does not validate science or automatically publish the structure.",
    auto_8c64c2a0e530: "Specific interaction of atomic pairs (ECIF).",
    auto_898e5bcf715e: "Hydrophobic and stereo contact interactions",
    auto_ed428b8dc80c: "Intermediate — complies with part of these heuristic rules",
    auto_fef3df333005: "Interpretation of the profile",
    auto_2033c07d6b2e: "Interval of",
    auto_e2dcdd634166: "kcal/mol — which in exponential scale are more than two orders of magnitude. The interval above is the maximum that this number holds. Use it to order anti-dianas against each other, not to decide if a concentration is safe.",
    auto_8c4ac216c830: "kcal/mol of the Vina score.",
    auto_222f750aceb4: "The Folder",
    auto_0af4040d3c39: "The password must have at least 8 characters.",
    auto_d03d4fc90d79: "The run started but his identifier could not be saved in the case.",
    auto_66c8de9b17f6: "The run does not correspond to the current inputs. Corrects the hypothesis or abstains.",
    auto_990cc7b4b8ec: "The run did not return a receptor or pose file that can be used to compare.",
    auto_5dc69e1ba19b: "The run is over and your evidence can be recovered.",
    auto_471ce73812dc: "The arrangement could not be saved. Check the justification.",
    auto_1e4b0441cf79: "The input does not pass a structural check. The reason is retained and the stage that cannot be executed is blocked; the case is not quietly removed.",
    auto_57d409b275d3: "The molecule was re-evaluated after certification: the seal attests to a previous run, not the one shown.",
    auto_d789b996261e: "The molecule was re-evaluated after recording its receipt. The chain retains a historical index of",
    auto_aca79297777a: "The path of the legal document does not belong to local assets.",
    auto_b5b351f33de7: "The table compares available evaluations against the same receptor. The similarity uses Tanimoto on the topological fingerprint of RDKit; deltas only appear when both runs retain the corresponding metric.",
    auto_567d82bb53d9: "The task was no longer active. We updated its status with the backend.",
    auto_ebb21b20058c: "Passwords don't match.",
    auto_35f6dace8ff1: "Lipinski’s four rules are historical filters for comparing oral compounds. Failure to comply with a rule does not rule out a molecule or amount to clinical toxicity or failure.",
    auto_db0393069f56: "It measures them again and replaces them. This artifact is not rewritten or re-sealed: it is preserved as it remained, so that the correction is auditable.",
    auto_6ed63fc9cfbb: "Unregistered flirting in this run",
    auto_5cc2fcbbbc9d: "Lipinski not calculated for this analogue",
    auto_52e9ae29fb89: "Lipinski passed — complies with drug-likeness rules",
    auto_2e5a9badd398: "What you write will come out of your machine towards",
    auto_a10f57b88037: "What docked",
    auto_8b8d19d6a005: "LogP describes the calculated distribution between aqueous and lipid phases. It is a descriptor dependent on method and chemical status; it does not predict permeability, circulation or efficacy alone.",
    auto_0310df6f0be2: "LogS is an estimate or measurement expressed in logarithmic scale according to the method used. Guidance ranges do not replace a solubility test under experimental conditions.",
    auto_cd20267c5ed3: "PAINS are common false positives in biological trials (Baell & Holloway, 2010). Exhaustive experimental validation is recommended before considering this molecule as a hit.",
    auto_e0d54255ddee: "Shared receptors are not available.",
    auto_aca2756d969d: "virtual machine or without GPU—and blocks the run forward while",
    auto_917ac7093911: "more",
    auto_ec0377945f92: "Mass of the molecule expressed in daltons. The threshold of 500 Da is an empirical rule of Lipinski to compare series; it does not guarantee absorption or exposure in a person.",
    auto_f63ac70bacae: "Maximum — use most of your CPU. Close other heavy applications",
    auto_a9b6fb847654: "Higher proportion sp3 — complexity descriptor",
    auto_2528775f013b: "Geometric mean of three factors derived from ADMET-AI: solubility, intestinal absorption and a term of toxicity based on the probability of hERG block. The constants that combine them are chosen by hand and not adjusted against clinical data. It serves to prioritize within a series and to see what term penalizes a molecule; it is not a prognosis of whether it survives in blood. In particular it does not incorporate the free Cmax / CI50 margin, which is what decides the real risk of hERG.",
    auto_00dbdddcb460: "Optional memo with hashes and technical metadata of a dossier. Test integrity and date of issue, no authorship, scientific validity or intellectual property.",
    auto_b76b56f0f66f: "Optional memo that records hashes and technical metadata from a dossier. You can prove which bytes were associated with a date and transaction; it does not validate science, does not certify authorship and does not replace local origin.",
    auto_a6c6215f575a: "method not registered",
    auto_29f1a0264265: "It measures how focused the molecule is on protein hotspots.",
    auto_ed5c43cd041b: "Same receptor and same run; show the actual SDF coordinates of the poses #",
    auto_530df92bc823: "Optional tabular model for cohorts and weights declared by a profile. It does not diagnose toxicity or identify patents for itself.",
    auto_605672b1cc3b: "Optional tabular model for specific experiments. It should only be shown when the manifest declares its weights, cohort and applicability; it does not detect patents or diagnose toxicity by itself.",
    auto_3c11e2b8db88: "Ultralight model ideal for PCs without GPU and very limited resources.",
    auto_c9284334afff: "D-MPNN models that produce signals on absorption, permeability and other endpoints. They are interpreted as computational predictions, not as clinical safety.",
    auto_bdfddc5eef10: "Machine learning models that produce signals about absorption, permeability, protein binding and other endpoints. The blood profile index is heuristic and serves to compare a series; it is not a clinical prognosis or a safety decision.",
    auto_4e5f58ee4e09: "Offline mode: enable web mode to enrich with PubChem/ChEMBL",
    auto_a3fa6f75da44: "Active Web mode: enriches with PubChem/ChEMBL and may take longer",
    auto_ca4cf793bc42: "Experimental module. It runs ON LOCAL, on this machine: the first",
    auto_a4e3d3490896: "AI and Physics Modules",
    auto_6be8b77110ff: "MolChat is responding...",
    auto_144067985189: "Show full receptor",
    auto_5ebc24194e17: "Empirical docking engine that explores poses inside a box and returns a Vina score. That score serves to order poses under the declared protocol; it is not an experimental free energy or an affinity guarantee.",
    auto_2e24a6f6267b: "Standard docking engine. Exhaustiveness=8. ~20s per ligand.",
    auto_d64c24cabf94: "No successes or failures: describe the terrain or declare the bet before looking.",
    auto_46c73e4fa1e0: "No case matches the search.",
    auto_f3beed6bd3c8: "Do not close the case without copying or retrying the save.",
    auto_1e6cb1e6dc11: "does not contain a",
    auto_271fb52e9981: "There are no analogs to compare. Evaluate more moleculas against this target.",
    auto_0e26df2c1c3d: "There is no attached molecular context.",
    auto_c922a83946da: "There are no declared metals for storage",
    auto_2159b50010ad: "There are no shared targets yet",
    auto_ade812f7939a: "There is no attached molecule. You can paste data into your message.",
    auto_47083d99db42: "not calculated",
    auto_632d94f6b658: "No coupler ligand was generated",
    auto_fafd22a23afe: "Could not load scientific 3D viewfinder (Mol*).",
    auto_ce72cf899871: "Could not check if engine ranking is supported for",
    auto_02aba466e282: "Could not connect to the community. Check your internet connection.",
    auto_129fd24eafd6: "Could not create case. Check the above notice: There may be an unsaved change in the current case.",
    auto_34d105ded9d6: "Could not create variant.",
    auto_96129f3bbb7a: "Could not close temporary folder: %s",
    auto_b2869e46ca45: "could not be moved and is still in the guest account; its results are already yours.",
    auto_f56cc2a1ae4e: "Could not close temporary folder: %s",
    auto_7d87ae35f871: "No content-addressed snapshot was recorded for this run.",
    auto_da60d4d5d247: "Number of acceptor atoms according to chemical representation. HBA ≤ 10 is a Lipinski criterion for comparing compounds, not a guarantee of oral absorption.",
    auto_062fc71dfbbf: "Number of rotatable bonds defined by the descriptor. High values can be associated with greater conformational flexibility, but do not prove instability or prevent docking.",
    auto_1e01fec6e93b: "Number of groups able to donate hydrogen according to chemical representation. HBD ≤ 5 is a Lipinski criterion for comparing compounds, not a guarantee of oral absorption.",
    auto_2f66c748dbd5: "Total number of intimate atomic collisions and interactions. Strong spatial lace indicator.",
    auto_174b86a69af7: "Total number of contacts on the first and second pocket solutation dial.",
    auto_519ddde05991: "Or continue with",
    auto_7a2d6cf4994c: "Hide receptor (leave only active site + grid)",
    auto_b0487918dd42: "Hide the molecule (linking coupled)",
    auto_eef39378ea52: "Hide lines of interaction (H-bonds, hydrophobics...)",
    auto_f08ea8842a9f: "happens. It is NOT necessary for docking: off, docking and",
    auto_67bfa12d71a2: "An unexpected error occurred while uploading the receptor.",
    auto_e57566562d4e: "There was an unexpected error in this component.",
    auto_ea5a09df6c44: "OH; H-bonds, methyl-restricted geometry.",
    auto_98c1ad5d0471: "A radial wave mathematically synchronized with the activation of the modules.",
    auto_d1728e225254: "orders of magnitude, derived from score with ±",
    auto_1f9342007908: "Pair compatible with a hydrogen bond, but ECIF has contacts within a cut-off radius: it does not check geometry or angle.",
    auto_7080a733bfcd: "Pair donor-acceptor compatible with hydrogen bond, counted by distance and without geometry.",
    auto_fe965110a196: "Pair donor-acceptor compatible with hydrogen bond. ECIF counts it by distance, without checking the angle D-HA.",
    auto_f2cfe47391ae: "Unregistered engine parameters",
    auto_ad2f27e22451: "Pairs between ligand aliphatic carbon atoms and pocket oxygens. Capture dipole-dipole interactions and H bridges with acceptors.",
    auto_2def3ff0a99f: "Part of",
    auto_c025cd216bcf: "Pause Simulation",
    auto_b3db787af1a3: "Common penalties: Weight > 500 Da, LogP > 5, more than 10 rotations.",
    auto_4a460dbb24e9: "Please name your receptor.",
    auto_b612f6dc223e: "Please select a biological target (Target) from the catalog before starting the simulation.",
    auto_f4fdb640f385: "Because the molecule has given an unfavorable result. The rest of the evaluation — docking, poses and physical controls — does not depend on this block.",
    auto_17a9283c624b: "PPB is a category derived from a model or descriptor. The free fraction depends on concentration, matrix and conditions; it is not enough to conclude distribution or activity.",
    auto_38997db9a692: "Prediction of solubility, intestinal absorption, BBB, plasma protein binding",
    auto_9d931f7fadb2: "pharmacokinetic prediction instead of showing an invented one.",
    auto_32a9d49fe4e0: "Questions about structural evidence",
    auto_16f46113d69c: "Question about the attached molecule",
    auto_df93272641f2: "Questions with acceptance criteria declared before, which exceeded it.",
    auto_9385e5fdcc30: "Prepare molecular hypotheses, explore poses, and document the computational evidence of each run.",
    auto_7f97a774bf43: "Origin of signals ·",
    auto_f5681aafed47: "Physical-chemical property extracted from the molecular complex.",
    auto_129ae70d08f8: "Try the light viewfinder from the viewfinder button: you need a lot less from the computer.",
    auto_03d50be324c8: "You can enter the PDB ID manually.",
    auto_5bdde6ca20b7: "Input point to the accelerator. Supports mass intake in batches (CSV/SDF) or individual chains. Immediate tokenization for the validation pipeline.",
    auto_a0adb4d99412: "QED combines several descriptors on a historical scale of drug-likeness. A high value indicates closeness to that heuristic, not approval, safety or causal similarity with drugs.",
    auto_842dd575a113: "which is not installed locally.",
    auto_abd7ce809ba9: "Qwen2.5-1.5B served locally when the model is installed. You can consult persistent evidence and explain states, but it is not the primary source of results, it does not involve local voice and runs without network only after downloading the model.",
    auto_afc96853778b: "Range of scores between poses",
    auto_dabe6e993bad: "More advanced scientific reasoning requires better processor/RAM.",
    auto_38522fe5e383: "Neuronal network of graphs to produce a recoring signal when the model, its weights and its cohort are declared. Metrics and any claims about bias depend on the specific partition and benchmark; they are not generalized to all molecules.",
    auto_00cf99ca43b6: "REDUCE the predicted affinity",
    auto_4a70388e7d39: "Rule of the Lipinski 5",
    auto_3db8386c07e1: "Veber Rules",
    auto_932951364a43: "Regression or classification on features of a pose when there is a valid profile and domain of applicability. Its output is a derivative interpretation; it does not replace the observed score of Vina out of domain.",
    auto_c1f4fae31eb5: "Regression on features of pose when there is a valid profile and domain. Output is a derivative interpretation, not a universal correction of Vina.",
    auto_3363d78ec95f: "Reminimizes the actual docking pose with OpenMM and subtracts the isolated receptor and ligand energies.",
    auto_7b77d6194b7b: "Play Simulation",
    auto_000b59c99346: "Rescoring derived from features of the pose when the profile and its domain are available. The output can be expressed in pKi and kcal equivalents according to the protocol; outside the domain the observation of Vina prevails.",
    auto_d7714baeba50: "Residue from the active site.",
    auto_0216bf13df20: "Small residue, contributes to hydrophobic packing of the pocket.",
    auto_3b64bc4ca408: "Review of alerts",
    auto_1e917b222b05: "Rigid; defines turns, contributes to the shape of the site.",
    auto_ccc606b7ab22: "Ro5 of Lipinski:",
    auto_a0f1490a20d0: "s",
    auto_73ce5e0c984a: "Quitting the Stage",
    auto_6a23e1f9d80d: "Mastering Score of AutoDock Vina's best pose. A positive SHAP indicates that more related poses push the model score upwards.",
    auto_e930067de091: "The canonical tautomer of RDKit was chosen",
    auto_4750b49f870b: "It's downloading...",
    auto_69c1421c8782: "Protonated to pH",
    auto_51a229f168ca: "Select a persistent evaluation to consult comparable molecules against the same receptor. No examples or simulated results are shown.",
    auto_6f82b47554ca: "SELECTED TO SHARE",
    auto_5a961ba823b3: "Seal predating provenance recording: it does not record which run it certified.",
    auto_652200f9cc43: "SELLO WITHOUT CLOSING",
    auto_b75d71d7c486: "signal",
    auto_ff7cabb9c513: "Signal · zinc warheads (UMS, SMARTS):",
    auto_cf041ff07895: "Computational signal of permeability to BBB. It does not demonstrate live entry to the brain nor does it imply therapeutic benefit or risk.",
    auto_30f8b7d8b9a8: "Computational signal of permeability or intestinal absorption. Its result depends on the model and its domain; it does not predict human exposure alone.",
    auto_20ba0016e1e3: "Neuronal signal of graphs available only for profiles that declare model, weights and cohort. Metrics are conditional on benchmarking; it is not presented as a universal detector of bias or thermodynamics.",
    auto_9340a078aa31: "Yes, delete data",
    auto_1351ada0b9c9: "WITHOUT ADVICE",
    auto_806a2dd2c630: "No side chain; allows narrow spaces in the pocket.",
    auto_440fc8f92285: "No folder chosen.",
    auto_17ecdaf55d49: "No case",
    auto_280145ccad5c: "Unclassified — treat it as unverified",
    auto_85e292a64f4e: "No comparison",
    auto_185e750ee009: "no data",
    auto_01f70610d0a7: "no data in this run",
    auto_94135ee04adb: "Without GPU — CPU:",
    auto_14009a618e8d: "no ID",
    auto_a9b0c58ab88e: "WITHOUT CONTENTS",
    auto_fe9905aee429: "No interactions: run the evaluation to analyze ligand contacts",
    auto_abcb7f140cae: "No molecule: run the evaluation to see the coupled ligand",
    auto_310c64678aed: "no result",
    auto_1ce84036ee8b: "No results for this search",
    auto_09e250071934: "Smart sampling, 2-3× faster than Vina. Same precision.",
    auto_396af15df54e: "Snapshot content-addressed preserved; the local route remains private.",
    auto_e66cbf48ffa4: "your identifier so you can recover it with the correct session.",
    auto_f78181f943ab: "Upload a public target to collaborate with the community.",
    auto_1b72f46cf978: "your scores are calculated the same, and the Parameters panel is left without",
    auto_a3f6d7df9f9f: "Box size (Å)",
    auto_faa74cbc60a9: "The available molecular context is also attached.",
    auto_3e3117216cff: "Target without name",
    auto_b5dacc17359a: "Tiol; can form covalent bonds with electrophilic warheads.",
    auto_da7c1fdae98a: "There are no cases yet.",
    auto_7cbf8c0d5ae1: "TPSA summarizes the polar topological surface. Lipinski and Veber thresholds are indicative and should be interpreted along with the rest of the profile; they do not determine the cellular or cerebral passage.",
    auto_c224ef74ad87: "Your molecular identity is being validated on the local server.",
    auto_7d5211dfd7ca: "Your session changed. The visible result was cleaned, but the finished run remains",
    auto_d63f7a54d93b: "Your session changed.The previous results were cleaned to avoid saving molecules from another account.",
    auto_b0a87dfd9e6e: "Your session changed. The previous results were cleaned so as not to mix them with another one.",
    auto_e5d485629017: "Affinity threshold",
    auto_c0f7ffa788c9: "a model",
    auto_0640a1e7f589: "A PAINS alert, an SA heuristic or other rule requires revision. It is preserved as evidence and does not automatically become toxicity or discard.",
    auto_fff211e08ae8: "An anti-target was not evaluated",
    auto_4afeaaad596e: "Validate structure, valence, chirality, conformants and physicochemical properties. These signals help to check an entry; they do not determine clinical viability alone or whether a molecule is a drug.",
    auto_05b7cb91f92b: "Validates sanitization, valence, aromaticity, and molecular representations. Signals are preserved for review; it does not decide on its own the viability of the compound.",
    auto_317bd150cc87: "Validates valence, chirality, conformers, and physicochemical descriptors. Their signals serve to review a structure; they do not determine for themselves whether it is a drug.",
    auto_f1f215ef3d12: "Variance between poses",
    auto_b296de8883ee: "Veber links rotatable bonds and TPSA with oral bioavailability in certain sets. It is a heuristic of prioritization, not an individual prediction of bioavailability.",
    auto_e5d668feb775: "See the molecule (linking coupled)",
    auto_1054995e158b: "See lines of interaction (H-bonds, hydrophobics...)",
    auto_2e80694bf926: "See why it requires revision",
    auto_fa699172d465: "Visualizing the complete sequential topology.",
    auto_dc96db7f7404: "Recheck the preparation before executing.",
    auto_faf5a356627c: "and this tab shows",
    auto_72ef951a4533: "is already registered in",
  },
};
