"""
services/ai/target_resolver.py

Centralized target name -> pdb_id resolution for MolChat (F4).

Purpose
-------
Users ask for docking against common names, not PDB IDs: "receptor de
serotonina", "beta-adrenergico", "CYP3A4", "SARS-CoV-2 Mpro". This module
resolves those names to the curated PDB ID the docking pipeline consumes.

Data source
-----------
backend/data/target_aliases.json — generated by scripts/build_target_aliases.py
from curated_targets.csv (clean names), curated_targets.json (names + family),
PDB COMPND SYNONYM headers (biological aliases), and curated Spanish/INN
aliases. 387 targets, 303 with aliases, all with local structure.

Resolution chain (early return on first success)
------------------------------------------------
    1. PDB ID exact match        ("7E2Y" -> 7E2Y)
    2. Alias exact match         (normalized alias == normalized query)
    3. Token overlap scoring     ("receptor de serotonina" scores 7E2Y high
                                 because aliases contain "serotonina" and
                                 "receptor")
    4. Fuzzy match on aliases    (difflib, cutoff 0.78 — catches typos like
                                 "receptor de serotonita")
    5. No resolution -> structured failure with available-target hint

Privacy / I/O
-------------
Fully local: reads only the generated JSON (no network, no DB). The caller
decides what to do with the returned pdb_id (run_docking etc.).
"""

from __future__ import annotations

import difflib
import json
import re
import unicodedata
from dataclasses import dataclass
from pathlib import Path

# ---------------------------------------------------------------------------
# Data loading (lazy, cached)
# ---------------------------------------------------------------------------

_ALIASES_PATH = (
    Path(__file__).resolve().parent.parent.parent / "data" / "target_aliases.json"
)

_load_lock = None  # trivial module-level cache is fine for read-only data
_loaded: dict[str, dict] | None = None


def _norm(s: str) -> str:
    """Lowercase, strip accents, collapse whitespace (matching key form)."""
    if not s:
        return ""
    nf = unicodedata.normalize("NFKD", s)
    stripped = "".join(ch for ch in nf if not unicodedata.combining(ch))
    return " ".join(stripped.lower().split())


def _load_aliases(path: Path | None = None) -> dict[str, dict]:
    """Load target_aliases.json once and cache by pdb_id (upper)."""
    global _loaded
    p = Path(path) if path else _ALIASES_PATH
    if _loaded is not None:
        return _loaded
    if not p.exists():
        return {}
    try:
        with open(p, encoding="utf-8") as f:
            entries = json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}
    result: dict[str, dict] = {}
    for e in entries:
        pid = (e.get("pdb_id") or "").strip().upper()
        if pid:
            result[pid] = e
    _loaded = result
    return result


def _aliases_for(entry: dict) -> list[str]:
    """The entry's alias list, plus the pdb_id itself and its short name."""
    out: list[str] = []
    for a in [entry.get("pdb_id"), entry.get("name")] + list(entry.get("aliases") or []):
        if a and isinstance(a, str) and a.strip():
            out.append(a.strip())
    return out


# ---------------------------------------------------------------------------
# Result type
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class TargetResolution:
    """Outcome of resolving a user-typed target name.

    Fields
    ------
    pdb_id : str | None
        Curated PDB ID if resolved, None if not.
    source : str
        "pdb_id" | "alias" | "tokens" | "fuzzy" | "failed".
    matched_name : str | None
        The alias (or PDB ID) that matched, for auditability.
    display_name : str | None
        The target's preferred short name (entry["name"]).
    family : str | None
        The target's structural family (gpcr, kinase, ...).
    error_hint : str | None
        User-facing suggestion when pdb_id is None.
    candidates : tuple[str, ...]
        Up to 3 close alternatives (pdb_id + display_name) when resolution
        failed — the caller can surface "¿quisiste decir ...?".
    """

    pdb_id: str | None
    source: str
    matched_name: str | None
    display_name: str | None
    family: str | None
    error_hint: str | None
    candidates: tuple[str, ...]


def _ok(pdb_id: str, source: str, *, matched_name: str | None = None,
        display_name: str | None = None, family: str | None = None) -> TargetResolution:
    return TargetResolution(
        pdb_id=pdb_id, source=source, matched_name=matched_name,
        display_name=display_name, family=family, error_hint=None,
        candidates=(),
    )


def _fail(raw: str, candidates: tuple[str, ...] = ()) -> TargetResolution:
    safe = (raw or "").strip() or "?"
    hint = (
        f"no reconozco el target '{safe}'. Usa el nombre común (ej: 'receptor "
        f"de serotonina', 'CYP3A4', 'JAK2') o un PDB ID directo (ej: '7E2Y')."
    )
    if candidates:
        hint += " ¿Quizás quisiste decir: " + "; ".join(candidates[:3]) + "?"
    return TargetResolution(
        pdb_id=None, source="failed", matched_name=None,
        display_name=None, family=None, error_hint=hint,
        candidates=candidates,
    )


# ---------------------------------------------------------------------------
# Matching helpers
# ---------------------------------------------------------------------------

# Stopwords: words that describe the docking intent, never a target identity.
_STOPWORDS = frozenset({
    "receptor", "receptores", "contra", "target", "proteina", "proteína",
    "enzima", "dockear", "docking", "afinidad", "calcular", "calcula",
    "dame", "quiero", "necesito", "cual", "cuál", "el", "la", "los", "las",
    "de", "del", "con", "para", "y", "o", "un", "una", "por", "que", "qué",
})


def _tokenize(s: str) -> set[str]:
    """Token set from a normalized string, minus stopwords."""
    return {t for t in re.findall(r"[a-z0-9]+", s) if t not in _STOPWORDS}


def _alias_token_index(entries: dict[str, dict]) -> dict[str, list[str]]:
    """Build once: token -> [pdb_ids whose aliases contain that token]."""
    index: dict[str, list[str]] = {}
    for pid, entry in entries.items():
        for alias in _aliases_for(entry):
            for tok in _tokenize(_norm(alias)):
                index.setdefault(tok, []).append(pid)
    return index


_token_index: dict[str, list[str]] | None = None


def _get_token_index(entries: dict[str, dict]) -> dict[str, list[str]]:
    global _token_index
    if _token_index is None:
        _token_index = _alias_token_index(entries)
    return _token_index


def _top_token_candidates(query: str, entries: dict[str, dict], limit: int = 5) -> list[str]:
    """Score pdb_ids by how many query tokens appear in their aliases."""
    q_tokens = _tokenize(_norm(query))
    if not q_tokens:
        return []
    index = _get_token_index(entries)
    scores: dict[str, int] = {}
    for tok in q_tokens:
        for pid in index.get(tok, []):
            scores[pid] = scores.get(pid, 0) + 1
    ranked = sorted(scores.items(), key=lambda kv: kv[1], reverse=True)
    return [pid for pid, _score in ranked[:limit]]


def _fuzzy_alias(query: str, entries: dict[str, dict]) -> str | None:
    """Fuzzy-match normalized query against every alias.

    cutoff=0.78: catches "receptor de serotonita" -> "receptor de serotonina"
    while rejecting distant collisions. Operates on the whole normalized alias
    so multi-token names compare like phrases.
    """
    q = _norm(query)
    if not q:
        return None
    best: tuple[float, str, str] | None = None  # (ratio, alias, pid)
    for pid, entry in entries.items():
        for alias in _aliases_for(entry):
            a = _norm(alias)
            if not a:
                continue
            r = difflib.SequenceMatcher(None, q, a).ratio()
            if r >= 0.78 and (best is None or r > best[0]):
                best = (r, alias, pid)
    return best[1] if best else None


def _best_token_candidate(query: str, entries: dict[str, dict]) -> tuple[str, str] | None:
    """Among top token candidates, return (pdb_id, matched_alias) for the one
    whose alias contains the MOST query tokens (exact token hit wins)."""
    q_tokens = _tokenize(_norm(query))
    if not q_tokens:
        return None
    best_pid: str | None = None
    best_count = 0
    best_alias = ""
    for pid in _top_token_candidates(query, entries, limit=8):
        for alias in _aliases_for(entries[pid]):
            a_tokens = _tokenize(_norm(alias))
            hits = len(q_tokens & a_tokens)
            if hits > best_count:
                best_count = hits
                best_pid = pid
                best_alias = alias
    if best_pid and best_count >= 1:
        return best_pid, best_alias
    return None


# ---------------------------------------------------------------------------
# Public orchestrator
# ---------------------------------------------------------------------------


def resolve_target(
    query: str,
    *,
    aliases_path: Path | None = None,
) -> TargetResolution:
    """Resolve a user-typed target name into a curated PDB ID.

    Fully synchronous and local (reads the generated target_aliases.json).
    Never raises: data-load failures surface as ``failed`` with a hint.
    """
    if not query or not isinstance(query, str):
        return _fail(query or "")

    raw = query
    normalized = _norm(query)
    if not normalized:
        return _fail(raw)

    entries = _load_aliases(aliases_path)
    if not entries:
        return _fail(raw, candidates=())

    # ---- Step 1: PDB ID exact match ------------------------------------
    pid_upper = raw.strip().upper()
    if pid_upper in entries:
        e = entries[pid_upper]
        return _ok(pid_upper, "pdb_id", matched_name=pid_upper,
                   display_name=e.get("name"), family=e.get("family"))

    # ---- Step 2: alias exact match (normalized) ------------------------
    for pid, entry in entries.items():
        for alias in _aliases_for(entry):
            if _norm(alias) == normalized:
                return _ok(pid, "alias", matched_name=alias,
                           display_name=entry.get("name"),
                           family=entry.get("family"))

    # ---- Step 3: token overlap scoring ---------------------------------
    token_hit = _best_token_candidate(query, entries)
    if token_hit:
        pid, alias = token_hit
        entry = entries[pid]
        return _ok(pid, "tokens", matched_name=alias,
                   display_name=entry.get("name"), family=entry.get("family"))

    # ---- Step 4: fuzzy match -------------------------------------------
    fuzzy_alias = _fuzzy_alias(query, entries)
    if fuzzy_alias:
        for pid, entry in entries.items():
            if fuzzy_alias in _aliases_for(entry):
                return _ok(pid, "fuzzy", matched_name=fuzzy_alias,
                           display_name=entry.get("name"),
                           family=entry.get("family"))

    # ---- Step 5: failure with close candidates -------------------------
    near: list[str] = []
    for pid in _top_token_candidates(query, entries, limit=3):
        e = entries.get(pid)
        if e:
            near.append(f"{pid} ({e.get('name') or '?'})")
    return _fail(raw, candidates=tuple(near))


def list_available_targets(limit: int = 20) -> list[str]:
    """Curated short names for surfacing available targets (family grouped)."""
    entries = _load_aliases()
    by_family: dict[str, list[str]] = {}
    for pid, entry in entries.items():
        fam = (entry.get("family") or "other").strip() or "other"
        name = (entry.get("name") or pid).strip()
        by_family.setdefault(fam, []).append(f"{pid} ({name})")
    lines: list[str] = []
    for fam in sorted(by_family):
        items = sorted(by_family[fam])[:limit]
        lines.append(f"{fam}: {', '.join(items)}")
    return lines


__all__ = ["TargetResolution", "resolve_target", "list_available_targets"]
